### ISSUE TITLE
signP2SHTransaction cannot spend from any previous transaction containing a segwit output

### ISSUE THREAD

**Issue by johnoliverdriscoll** [LedgerHQ/ledgerjs#103]
Attempting to spend from a previous transaction containing any segwit outputs (even when attempting to spend a non-segwit output from that previous transaction) throws an "Invalid status 6f01". Furthermore, any attempt to use signP2SHTransaction after that throws "Invalid status 6faa" until the bitcoin app is restarted on the Ledger device.

**Comment by martellalex** [comment]
I'm running into this issue. Tried reinstalling the ledger bitcoin app . . . tried different usb ports and cables . . . I have the latest firmware . . . tried different bitcoin clients . . . still getting the same issue . ..  .  what is the fix for this? thank you!

**Comment by bodymindarts** [comment]
I'm only just learning myself but from going through the code perhaps you have not set the flag correctly when calling
```
  splitTransaction(
    transactionHex: string,
    isSegwitSupported: ?boolean = false,
    hasTimestamp?: boolean = false
)
```
