### ISSUE TITLE
signP2SHtransaction signatures invalid

### ISSUE THREAD

**Issue by dhoffmann** [LedgerHQ/ledgerjs#108]
Working with BTC testnet, I'm unable to get valid signatures using `hw-app-btc` methods. Below is roughly how I'm getting the sig...

```js
const paths = ["48'/1'/0'/0/0"]
const rawTx = `0100000001b81e689d96472e827d441a55d73ed5130ca824f51f093f850be96d65eca74585000000006c004c69522102cf13834b9aaffd6c4c30a6ec6f5abe9e2c15252145976e0ad0336532476b7a1021031dc516d2ba5b1eb88fc5201a36b6b5d3ae9e160618e300905e62faede37c13522103478e502e22fe29259a532c58f0fde2775892c9abd9e35908b09a5f175fc47cb353aeffffffff02d517390b0000000017a914785b83ed9f30f429103278fbfda16629b45cc3a587a0860100000000001976a914cd9fac69facab045d05508faab7feaae02c6b21488ac00000000`
const redeemScript = `522102cf13834b9aaffd6c4c30a6ec6f5abe9e2c15252145976e0ad0336532476b7a1021031dc516d2ba5b1eb88fc5201a36b6b5d3ae9e160618e300905e62faede37c13522103478e502e22fe29259a532c58f0fde2775892c9abd9e35908b09a5f175fc47cb353ae`
const sequenceNumber = 4294967295
const splitTx = await btc.splitTransaction(rawTx)
const outputScript = await btc.serializeTransactionOutputs(splitTx).toString('hex')
const inputs = [ [splitTx, 0, redeemScript, sequenceNumber] ]
const signatures = await btc.signP2SHTransaction(inputs, paths, outputScript)
return signatures
```

The signature does not pass `ECDSA.verify`. I've initialized the multi-sig wallet using the xPub from `48'/1'/0'`. I've also tried this using standard `44'/1'/0'` path. Does the device support testnet signing?

**Comment by ayush-techracers** [comment]
Hi @dhoffmann ,
I'm experiencing the same issue, I have detailed it here- https://github.com/LedgerHQ/ledgerjs/issues/182
Can you look into it and help me understand the problem? I really need this.

**Comment by nickfogle** [comment]
@ayush-techracers and/ or @dhoffmann did either of you end up determining whether testnet signing is supported? The biggest issue I'm seeing here is that my testnet output addresses are automatically converted into mainnet addresses and I can't seem to find a way to prevent that from happening.

**Comment by ayush-techracers** [comment]
My entire tests were based on testnet so yes, it is supported. @nickfogle if you can detail your issue further, maybe I can help you.

**Comment by btchip** [comment]
You need to test with the Bitcoin Testnet application on the Nano S (available in the developers section of Ledger Manager) to display testnet addresses. Otherwise the signatures will be correct but addresses will be displayed with the wrong version encoded as you noticed.

**Comment by nickfogle** [comment]
Thanks @btchip and @ayushtechracers. I wasn’t aware of the bitcoin testnet application. I’ll download and perform more testing.

**Comment by dhoffmann** [comment]
You can use the main BTC application. Just ensure you're using the correct path for operations.

https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#examples

**Comment by nickfogle** [comment]
@btchip, @dhoffmann, and @ayush-techracers I'm still encountering this issue and it appears others are as well. I've added highly detailed steps for duping here under issue #188. Any thoughts or input would be greatly appreciated!
