### ISSUE TITLE
signing transaction with using example-browser 

### ISSUE THREAD

**Issue by wannabit-jayb** [LedgerHQ/ledgerjs#111]
**Is there any quick guide or example to integrate Bitcoin signing transaction into an existing web application?** 

I am testing to see if I could sign transaction on our existing web application with the Ledger.

Using the given example-node, it works great for both getting the bitcoin address and signing transaction.
[Browser Support : No]

Using the given example-browser, getting Bitcoin address works but not signing transaction.
[Browser Support : Yes, HTTPS supported web]

**Comment by wannabit-jayb** [comment]
Oh, let me console logs inside the hw-app-btc/lib/Btc.js to see where it ends.

**Comment by wannabit-jayb** [comment]
The browser test shows the following error on the Chrome web console:

```bash
Uncaught (in promise) TransportError {name: "TransportError", message: "Failed to sign with Ledger device: U2F OTHER_ERROR", stack: "Error↵    at new TransportError (https://ledgerjs-…d00edbf681c4d6f314.js:20484:13↵    at <anonymous>", id: "U2F_1", originalError: Error: Sign failed
    at makeError (https://ledgerjs-browser-test.firebaseapp.com/b9611695abef7dd00…}
```

I log every part inside the `createPaymentTransactionNew` method in @hw-app-btc/Btc.js to see how far it could go, it seems like it triggers an error when going through the below method.

```bash
return (0, _utils.foreach)(inputs, function (input) {
        console.log('Here [0]')
   return (0, _utils.doIf)(!resuming, function () {
          console.log('Here[1]') 
          return getTrustedInputCall(input[1], input[0]).then(function (trustedInput) {
          console.log('Here[2]') // Not showing on console
          var sequence = Buffer.alloc(4);
          sequence.writeUInt32LE(input.length >= 4 && typeof input[3] === "number" ? input[3] : DEFAULT_SEQUENCE, 0);
          trustedInputs.push({
          trustedInput: true,
          value: Buffer.from(trustedInput, "hex"),
          sequence: sequence
        });
  });
}.then()...
...
...
```

**Comment by gre** [comment]
mmh no clue. maybe @amougel knows ^

**Comment by amougel** [comment]
Have you set the browser support option to on on your device?

**Comment by wannabit-jayb** [comment]
@amougel 
Yes, I did. I successfully retrieve the bitcoin address from ledger device.

**Comment by amougel** [comment]
My bad, haven't read your post thoroughly... You have to know that if at some point your device respond with an internal error : 6fxx, you have to reset the app otherwise it' ll refuse answering further calls.

If you want an example for creating a payment tx, you can find it one [here](https://github.com/LedgerHQ/ledger-wallet-webtool/blob/15cd99ced1ea9b110827c89a03fe16b2490fa4fc/src/TransactionUtils.js#L189)

**Comment by wannabit-jayb** [comment]
Yes, whenever I get that respond of 6fxx, I reset the app.

But, i don't think that is the issue for triggering an error.

> TransportError: Failed to sign with Ledger device: U2F OTHER_ERROR

Below source codes are what I used to test.

**index.html**
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>🚀 Ledger example </title>
  </head>
  <body>
    <hr>
    <div id="sign"></div>
      <script src="./sign.js"></script>
    <hr>
  </body>
</html>
```

**sign.js (I use `createPaymentTransactionNew` method to sign a transaction)**
```
class App extends Component {
  state = {
    output: null,
    error: null
  };
  onSigningTx = async () => {
    try {
      this.setState({ error: null });
      const transport = await TransportU2F.create();
      transport.setDebugMode(true);
      const btc = new Btc(transport);
      const tx1 = btc.splitTransaction("UTXO rawtransaction id");
      const txOut = btc.splitTransaction("Createrawtransaction output");
      const outputScript = btc.serializeTransactionOutputs(txOut).toString('hex');
      const { output } = await btc.createPaymentTransactionNew(
        [[tx1, 0],
        ["Ledger Bitcoin Address Derivation Path"],
        undefined,
        outputScript
      );
      this.setState({ output });
    } catch (error) {
      this.setState({ error });
    }
  };

  render() {
    const { output, error } = this.state;
    return (
      <div>
        <button onClick={this.onSigningTx}>
          Sign Transaction
        </button>
        <p>
          {error ? (
            <code className="error">{error.toString()}</code>
          ) : (
            <code className="output">{output}</code>
          )}
        </p>
      </div>
    );
  }
}

ReactDOM.render(<App />, document.getElementById("sign"));
```

**Comment by wannabit-jayb** [comment]
So, below codes are not the correct way to sign a transaction?

```
const transport = await TransportU2F.create();
      transport.setDebugMode(true);
      const btc = new Btc(transport);
      const tx1 = btc.splitTransaction("UTXO rawtransaction id");
      const txOut = btc.splitTransaction("Createrawtransaction output");
      const outputScript = btc.serializeTransactionOutputs(txOut).toString('hex');
      const { output } = await btc.createPaymentTransactionNew(
        [[tx1, 0],
        ["Ledger Bitcoin Address Derivation Path"],
        undefined,
        outputScript
);
```

Using node, it works well. I already tested it to sign a transaction and broadcast it to the network.

```
import TransportNodeHid from "@ledgerhq/hw-transport-node-hid";
import Btc from "@ledgerhq/hw-app-btc";

async function signTx() {
  const transport = await TransportNodeHid.create();
  const btc = new Btc(transport);
  const tx1 = btc.splitTransaction("");
  const txOut = btc.splitTransaction("");
  const outputScript = btc.serializeTransactionOutputs(txOut).toString('hex');
  const result = await btc.createPaymentTransactionNew(
    [[tx1, n],
    ["Derivation path"],
    undefined,
    outputScript
  );
  console.log("result: " + result);
}
```

Let me check out the [ledger-wallet-webtool](https://github.com/LedgerHQ/ledger-wallet-webtool). Thank you.

**Comment by wannabit-jayb** [comment]
@amougel 
Do you know if sending token transaction, such as Qtum-based dapps token works, too?
I am currently going through the codes in [Transfer Funds](https://ledgerhq.github.io/ledger-wallet-webtool/).

**Comment by amougel** [comment]
@wannabit-jayb  My bad, you can indeed create an Outputscript the way you did (the fact that it worked for you just proves it....)

I currently don't know how to or if we can create token transactions. I only used ledgerjs btc package
