### ISSUE TITLE
How to get the xpub

### ISSUE THREAD

**Issue by zekylaf** [LedgerHQ/ledgerjs#114]
Hi, I am using @ledgerhq/hw-app-btc package but I can't get the xpub from ledger blue wallet. Is there anyway to do it?

Thanks!

**Comment by gre** [comment]
it's not currently provided by hw-app-btc package.

I guess the most recent code we have written (by @loeck & @amougel) is this one: https://github.com/LedgerHQ/ledger-wallet-desktop/blob/2db4cabf071d5bd0db7f36df5fcb67214124e5d2/src/internals/usb/wallet/accounts.js#L42-L57 and it's usage here https://github.com/LedgerHQ/ledger-wallet-desktop/blob/2db4cabf071d5bd0db7f36df5fcb67214124e5d2/src/internals/usb/wallet/accounts.js#L85-L139 (AFAIK it's not in any library yet).

**Comment by gre** [comment]
we are planning a refactoring on the btc library, it's unsure yet if this refactoring will include computing the xpub but it's probably an important use-case.

**Comment by zekylaf** [comment]
Hi, I tried to use the code that you send me but the 'helpers/btc' repo is private. Do you own that repo? Can you send me an invite? 

Thanks!

**Comment by gre** [comment]
we use a special webpack resolver helper/btc is actually the same project https://github.com/LedgerHQ/ledger-wallet-desktop/blob/2db4cabf071d5bd0db7f36df5fcb67214124e5d2/src/helpers/btc.js

**Comment by zekylaf** [comment]
Ok, thanks a lot!
