### ISSUE TITLE
Unable to sign Stellar transactions (DecoratedSignature problem)

### ISSUE THREAD

**Issue by bazyli** [LedgerHQ/ledgerjs#121]
According to the example, signing with Ledger wallet should be decorated afterwards with proper hint, using standard stellar-sdk javascript library.

There's a problem however, that pushed decorated signature (using example code) always ends up with double-dipping of signature attribute.

In other words, instead of an entity looking as follows:
```javascript
"_attributes": { "hint": { "type": "Buffer", "data": [<data here>] }, "signature": {"type": "Buffer", "data": [<data here>] }
```
...we end up with a Frankenstein looking like this:
```javascript
"_attributes": { "hint": { "type": "Buffer", "data": [<data here>] }, "signature": {"signature": {"type": "Buffer", "data": [<data here>] }}
```
P.S. I'm using nodejs version for now, that is *hw-transport-node-hid*

**Comment by gre** [comment]
@lenondupe any thoughts on this? thanks

**Comment by bazyli** [comment]
There's a solution I found out working (so far). Instead of encapsulating hint and signature in decorated signature, I've added hint to signature object created by ledger call. 

i.e.:

```javascript
  const signature = await str.signTransaction("44'/148'/0'", transaction.signatureBase());
  
  // add signature to transaction
  const keyPair = StellarSdk.Keypair.fromPublicKey(publicKey);
  signature.hint = keyPair.signatureHint();
  const decorated = new StellarSdk.xdr.DecoratedSignature(signature);
```

And that seems to work. For now.

**Comment by lenondupe** [comment]
Yeah, seems the documentation is unclear or wrong. To get to the signature you need to do

```javascript
const result = await str.signTransaction("44'/148'/0'", transaction.signatureBase());
const signature = result.signature;
```
After that you can do
```javascript
  const keyPair = StellarSdk.Keypair.fromPublicKey(publicKey);
  const hint = keyPair.signatureHint();
  const decorated = new StellarSdk.xdr.DecoratedSignature({hint: hint, signature: signature});
```

**Comment by bazyli** [comment]
Sorry, but this is what I had done (apart from minor issue from naming variables in the doc, this is what the doc says).

And _it_doesn't_work_. This is why I've risen this issue. In order to make it work, I had to make actions as mentioned above, to ommit double-dipping of signature attribute in decorated signature.
