### ISSUE TITLE
TransportError id : "InvalidChannel" on hw-app-str electron app.

### ISSUE THREAD

**Issue by mcomgame** [LedgerHQ/ledgerjs#130]
Hi
I like to developing electron app using Ledger to signing stellar for feature. Using "hw-app-str" lib to test with code 

```
const getStrAppVersion = async () => {
            const transport = await Transport.create();
            const str = new Str(transport);
            const result = await str.getAppConfiguration();
            console.log(result)
        }
        getStrAppVersion();
```
With Ledger firmware version 1.4.1 
MCU 1.5

With Stellar App version 2.0.2

in "package.json" i use only
"@ledgerhq/hw-app-btc": "^4.7.3",
"@ledgerhq/hw-app-str": "^4.7.3",
"@ledgerhq/hw-transport-node-hid": "^4.7.3",

Got error massage
`TransportError {name: "TransportError", message: "Invalid channel", stack: "Error↵    at TransportError (/Users/admin/Document…lib/TransportNodeHid.js:295:34↵    at <anonymous>", id: "InvalidChannel"}`

I already open app inside the ledger when i test it.

But it working well on bitcoin with "hw-app-btc" lib.
I can get information from this code

```
       const getBtcAddress = async () => {
          const transport = await Transport.create();
          const btc = new AppBtc(transport);
          const result = await btc.getWalletPublicKey("44'/0'/0'/0");
          return result.bitcoinAddress;
        };

        getBtcAddress().then(a => {
          console.log('Success');
          console.log(a)
        });
```

what did i do wrong. please help me

**Comment by gre** [comment]
can you check in your device str app settings you have set Browser Support to NO ? (in case of node-hid)

**Comment by mcomgame** [comment]
Thanks gre 
I already set Browser Support to yes. It work with stellar site
https://www.stellar.org/account-viewer/
I can sign with it.

However it still not work on my electron app
Do you have any example electron app that work on ? Maybe i can study with it

**Comment by gre** [comment]
if you use U2F / web => Browser Support need to be set to YES
if you use node-hid => Browser Support need to be set to NO

you said you set browser to YES. it won't make the device work in node-hid because you need to set to NO.

> NB in future, this will disappear (already like in Btc app) as the device will support both communication at the same time

**Comment by mcomgame** [comment]
It work now.
Thanks a lot.
