### ISSUE TITLE
web3-subprovider fails to webpack with create-react-app

### ISSUE THREAD

**Issue by rsmylskibc** [LedgerHQ/ledgerjs#135]
When running build with create-react-app, it fails to build because of the inclusion of `web3-provider-engine/subprovider/hooked-wallet`, which is not es5 transpiled.

Now that https://github.com/MetaMask/provider-engine/pull/219 is in, web3-provider-engine now has es5 transpiled versions in their dist folders.

If the import is updated to reference `web3-provider-engine/dist/es5/subprovider/hooked-wallet` - it can be included in react apps without issue.

Thanks

**Comment by alxmhe** [comment]
Currently you have to specifically install and use version 14.0.4 of web3-provider-engine :
https://github.com/MetaMask/provider-engine/issues/239

**Comment by gre** [comment]
I think this is now fixed (version `5.2.0`)
