### ISSUE TITLE
Ledger Device Freezes when Calling CreatePaymentTransactionNew on BTC

### ISSUE THREAD

**Issue by MattC-IPayYou** [LedgerHQ/ledgerjs#138]
Hey guys,
I am using the BTC app with u2f transport and I have an issue where the device freezes anytime I call CreatePaymentTransactionNew at the sign step. The device freezes immediately and never asks for confirmation.

here is my initial reddit thread describing the issue:
https://www.reddit.com/r/ledgerwallet/comments/8acbfw/using_ledgerjs_to_sign_a_transaction_from_browser/?utm_content=title&utm_medium=hot&utm_source=reddit&utm_name=ledgerwallet 

Attached is my full ledgerapi.js file.  There are light edits to the final file as the source i run webpack on seems to use "this" inside promises instead of "self" causing undefined errors (inside the ledger source).

[ledgerapi.zip](https://github.com/LedgerHQ/ledgerjs/files/1921166/ledgerapi.zip)

Here are the values for transactions, keysets, changepath, and outputscript for createpaymenttransactionnew
var transactions = [["01000000012aa4b3ed04c950a2ae2d38f27ae3b90480742aafbd0abf8ef4fe9ad0c1e8d05401000000fdfd00004830450221008b1e5eefff9dde1aff1d41cb0fa844a90c52a26bd2ebac69fdd3a7fc3260097f02203c71eeff5e02469bcb2f63d957f2155aa81b70ba71328fc83e37fcb2493bfd0e0147304402200c59703ece11710347841d3d7c785d28ecc85722a35f37e883b6689164b3c53c022023d649b8ade06f7104d136e4e219a3d0463e519bc9924175a2fae8a3886b0858014c6952210266d03127a51b37595bab215e7322081cf7f709748525b3b6587088ee0ef626d821038da3f0fe972bf51606d1a2b28bf62c7a31b2c27d9b514520d17a138e1592260d210258c25e4d27e86ec8eacbd3b465905d22dbf4138b87ef559dbe05dea090c1e76953aeffffffff02955e0400000000001976a914f053737b39f9d26b563d38615df6edc635e0654288ac292d0c000000000017a9146a07f3e1f570a7be2ced2354c45181e7e25607cb8700000000",0]];

var keySets = ["44'/0'/0'/0"];
var changePath = "44'/0'/0'/1/0";
var outputScript = "753904000000000017a9146a07f3e1f570a7be2ced2354c45181e7e25607cb87";

And here are some logs of the CreatePaymentTransactionNew call, I notice the device never responds at the end.
ledgerapi.js?ver=249:7524 => e042000009000000000100000001
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e0428000272aa4b3ed04c950a2ae2d38f27ae3b90480742aafbd0abf8ef4fe9ad0c1e8d05401000000fdfd00
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e042800032004830450221008b1e5eefff9dde1aff1d41cb0fa844a90c52a26bd2ebac69fdd3a7fc3260097f02203c71eeff5e02469bcb
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e0428000322f63d957f2155aa81b70ba71328fc83e37fcb2493bfd0e0147304402200c59703ece11710347841d3d7c785d28ecc85722a3
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e0428000325f37e883b6689164b3c53c022023d649b8ade06f7104d136e4e219a3d0463e519bc9924175a2fae8a3886b0858014c695221
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e0428000320266d03127a51b37595bab215e7322081cf7f709748525b3b6587088ee0ef626d821038da3f0fe972bf51606d1a2b28bf62c
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e0428000327a31b2c27d9b514520d17a138e1592260d210258c25e4d27e86ec8eacbd3b465905d22dbf4138b87ef559dbe05dea090c1e7
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e0428000076953aeffffffff
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e04280000102
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e042800022955e0400000000001976a914f053737b39f9d26b563d38615df6edc635e0654288ac
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e042800020292d0c000000000017a9146a07f3e1f570a7be2ced2354c45181e7e25607cb87
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e04280000400000000
ledgerapi.js?ver=249:7533 <= 32003a2f5ef31cb3ef821955c8eb228f02ff117019f52b44d7944fa7480d741e2ff408cd00000000955e0400000000005d034004383589f69000
ledgerapi.js?ver=249:7524 => e040000011048000002c800000008000000000000000
ledgerapi.js?ver=249:7533 <= 4104bf09bc294e6d6b08c4b4fd6cb9ff1848c8de007d272fdfc8c2af1142aed1a11aea248a887f412a32bbfef1ec1a0e49ad019e8aac0ca0b7c70b77f020c25b0bec22314e756a394b6b64397746696173535879703748783168726379736635705a336d5aae5cb50c5570da016f132f450e6e53ae76e4acfc89d775ccd3c325c565a272309000
ledgerapi.js?ver=249:7524 => e0440000050100000001
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e04480003b013832003a2f5ef31cb3ef821955c8eb228f02ff117019f52b44d7944fa7480d741e2ff408cd00000000955e0400000000005d034004383589f619
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e04480001d76a914f053737b39f9d26b563d38615df6edc635e0654288acffffffff
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e04aff0015058000002c80000000800000000000000100000000
ledgerapi.js?ver=249:7533 <= 9000
ledgerapi.js?ver=249:7524 => e04a8000209df903000000000017a9146a07f3e1f570a7be2ced2354c45181e7e25607cb87
ledgerapi.js?ver=249:7533 <= 00009000
ledgerapi.js?ver=249:7524 => e048000017048000002c800000008000000000000000000000000001

**Comment by bwheeler96** [comment]
I've noticed the ledger can freeze if a user opens multiple tabs and each tab calls the ledger separately. I'm going to make a separate issue for it but I think its related.

**Comment by gre** [comment]
I think it might be related to what @bwheeler96 mentioned, and in fact likely related to U2F. There are no possible solution from ledgerjs point of view of preventing a user to do multi-tabs but it can be solved at the technology/browser level, which I think is what WebUSB/WebHID guarantees (when you create the connection, others can't take it).
