### ISSUE TITLE
XRP trustlines, IOU payments

### ISSUE THREAD

**Issue by sammy007** [LedgerHQ/ledgerjs#141]
Is it possible to set trustlines, transfer tokens with ledger or only XRP transfers?

```
  const trustline = {
    "currency": "EUR",
    "counterparty": issuerAddress,
    "limit": "100000000"
  }
  const json = JSON.parse((await api.prepareTrustline(myAddress, trustline, instructions)).txJSON);
  const rawTx = Bin.encode(json);
  let txJSON = Bin.decode(rawTx);
  txJSON.TxnSignature = (await xrp.signTransaction("44'/144'/0'/0/0", rawTx, false)).toUpperCase();
  txJSON.SigningPubKey = result.publicKey.toUpperCase();
  console.info(txJSON);
  api.submit(Bin.encode(txJSON));
```

Getting just `UnhandledPromiseRejectionWarning: Error`
`@ledgerhq/hw-transport/lib/Transport.js:152:16`

Nothing appears on device screen. I am guessing it's because device does not support such transactions and only recognises plain XRP transfers. Is it the case or I am doing it wrong?
If it's the case, is there any plans to add support for trustlines and IOU transfers to ledger?

**Comment by btchip** [comment]
you're right, the application doesn't support those transactions yet. A PR to https://github.com/ledgerhq/blue-app-xrp would be welcomed.

**Comment by sammy007** [comment]
@btchip honestly, it will take titanic effort from me. Would ledger consider adding such "extensions" themselves? The rationale is obvious, XRP is a "gas" and literally storing it securely is a tiny part of ripple/ledger use cases, what is really useful is to store IOU tokens (like erc20), set trustlines and trading. The xrp exchange is widely used, there is a lot of activity. The possible positive outcome for ledger is that you can probably try to partner with services like https://gatehub.net/ and introduce a secure way to access and use it because currently their users must provide their private keys or use hosted wallets in order to use it which is totally insane and insecure.

**Comment by btchip** [comment]
we might have a look at some point. I'm closing this issue, you can monitor the other application project to see if/when it's done.
