### ISSUE TITLE
Example code in hw-app-str/README.md does not run

### ISSUE THREAD

**Issue by Ratniex** [LedgerHQ/ledgerjs#142]
link to lib: https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-app-
```
// example.js
const _Transport = require("@ledgerhq/hw-transport-node-hid");
const _Str = require("@ledgerhq/hw-app-str");
const Transport = _Transport.default
const Str = _Str.default
console.log(Transport, Str);

const getStrAppVersion = async () => {
    const transport = await Transport.create();
    console.log('transport', transport);
    const str = new Str(transport);
    console.log('str', str);
    const result = await str.getAppConfiguration();
    console.log('result', result);
    return result.version;
}
getStrAppVersion().then(v => console.log(v));

```
The code was run with `node example.js`
Node version used was 9.3.0
The code hangs at line `const result = await str.getAppConfiguration();`
Ledger device works when used with this web based wallet https://www.stellar.org/account-viewer/

**Comment by gre** [comment]
have you set "browser support NO" to test with the node-hid impl?

**Comment by Ratniex** [comment]
Probably not, however I do not know what is this "browser support NO" that you speak of.

**Comment by gre** [comment]
in Settings of the Stellar app, there must be a setting called "Browser Support" . it needs to be set YES for browser and NO for node.
(I don't know if Stellar have moved yet to latest sdk but in recent development, this setting will be gone as apps will directly support u2f et hid at the same time)

**Comment by Ratniex** [comment]
Thank you, this solved my problem. Consider these changes to the readme
[0001-fix-example-code-in-packages-hw-app-str-README.md.patch.txt](https://github.com/LedgerHQ/ledgerjs/files/1946108/0001-fix-example-code-in-packages-hw-app-str-README.md.patch.txt)

**Comment by gre** [comment]
would you like to create a PR ? thanks

**Comment by Ratniex** [comment]
https://github.com/LedgerHQ/ledgerjs/pull/143
