### ISSUE TITLE
Support Testnet derivations in web3-subprovider

### ISSUE THREAD

**Issue by jamespic** [LedgerHQ/ledgerjs#144]
`web3-subprovider` only allows derivations that begin with `44'/60'` or `44'/61'`. Adding `44'/1'` would enable testnet accounts to be derived appropriately.

**Comment by gre** [comment]
@jamespic good point! can you send a PR ?
thanks

**Comment by jamespic** [comment]
Yep, can do.

I couldn't find the tests for `web3-subprovider`. What approach should I take to testing?

**Comment by gre** [comment]
we don't have much test yet for web3-subprovider but you can test if it works with the dapp starter. we will try to improve tests later (but mainly we are waiting to have a ledger simulator so we can headless-ly run tests)

I think you can send a PR as it's probably just changing one line of code , should be fine
