### ISSUE TITLE
Intermittent 'cannot open device with path' error

### ISSUE THREAD

**Issue by wbobeirne** [LedgerHQ/ledgerjs#146]
When using `hw-app-eth` to sign transactions via `app.signTransaction(path, tx)`, I sometimes get the following error:

> Error: cannot open device with path IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/Nano S@14200000/Nano S@0/IOUSBHostHIDDevice@14200000,0

I've googled around and seen it in a few places:

* https://www.reddit.com/r/NEO/comments/7cx8l3/neon_ledger_nano_help/
* https://github.com/porsager/busylight/issues/7

So it's definitely happening to others, but I can't pin it down. As far as I know, no other app is trying to access the device, and it's not for all calls. Anyone know what this might be?

**Comment by wbobeirne** [comment]
This one's on me; I wasn't trying to open up a new transport for each call, rather than closing out or reusing my existing transport object. That fixed this up.

**Comment by fedecaccia** [comment]
Thanks @wbobeirne that was exactly my problem!
