### ISSUE TITLE
hw-app-str doesn't work with angular 6

### ISSUE THREAD

**Issue by phra** [LedgerHQ/ledgerjs#154]
angular 6 removed from webpack configuration nodejs core modules shims.. see https://github.com/stellar/js-stellar-base/issues/128 and https://github.com/angular/devkit/issues/967#issuecomment-391385515

i managed how to make stellar sdk work including the compiled version instead of the sources.

now my app fails with `hw-app-str` package because the code is depending on webpack that is not importing nodejs core modules shims:

![image](https://user-images.githubusercontent.com/984628/40438656-e83a7278-5eb8-11e8-9fab-87bc60ffcebb.png)

**Comment by gre** [comment]
if i'm correct this works because crc dependency that depends on "buffer" https://github.com/alexgorbatchev/node-crc/blob/master/src/crc16_xmodem.js#L1

it depends on "buffer" implicitely? because i'm not seeing a direct dependency, weird.

Have you tried to add a dependency to "buffer" in your top level project?

```
    "buffer": "5.1.0",
```

**Comment by phra** [comment]
@gre explicitly depending on `buffer` should fix the problem.
atm in my angular application the `buffer` library is included by `angular-devkit` and it's 4.x version, that doesn't work in the browser without nodejs shims.

![image](https://user-images.githubusercontent.com/984628/40486023-663e1fce-5f60-11e8-9560-5094d458a359.png)

and not by `node-crc`

![image](https://user-images.githubusercontent.com/984628/40486042-765cfd62-5f60-11e8-9842-1e55a25a9ca3.png)


see https://github.com/alexgorbatchev/node-crc/issues/53

**Comment by phra** [comment]
@gre i've sent #155 to solve the problem removing `node-crc` from the deps and backporting `crc16xmodem()` function.
