### ISSUE TITLE
BCH payment transaction fails to send

### ISSUE THREAD

**Issue by wannabit-booyoun** [LedgerHQ/ledgerjs#160]
Hi

I want to send BitcoinCash but the result fails.

I signed with Ledger NanoS and I use createPaymentTransactionNew function, P2PKH.

I installed Bitcoin Cash App on Ledger NanoS. I use both 44'/145'/0' and 44'/0'/0'.

The following raw transaction is the result of signing with Ledger NanoS. This signed transaction doesn't work.

`0100000001dea4c7e0fb0570fc4926884097ed6c3aeec71f8fd449fea61b4f489175ad11cf000000006b483045022100a25cac62fc849ed2e7e75c50465a509ec53540fb05fefc37f7ca2792b3f40264022015ab022d66f967ac0a54a8267a4c4a7c7496a2a17eb7aa44500df4dc1e720fd2412102f418d6148855a6c83068ba3397048e9fd3a824468f6b39622451a6a58cf8f4a0ffffffff02a0860100000000001976a914f2e270cf42acbd1653e014ebfd54294f718db88288ac1c24a600000000001976a914f348714f4956773f6731f190419b2db1e200ca2788ac00000000`

I did decode this raw transaction and it's fine. I can see right full transaction code.

`{
  "txid": "3b2b4dce6df03c430f16e9254b227ff3815554bdbe097a99c0709076e8b45b19",
  "hash": "3b2b4dce6df03c430f16e9254b227ff3815554bdbe097a99c0709076e8b45b19",
  "size": 226,
  "version": 1,
  "locktime": 0,
  "vin": [
    {
      "txid": "cf11ad7591484f1ba6fe49d48f1fc7ee3a6ced9740882649fc7005fbe0c7a4de",
      "vout": 0,
      "scriptSig": {
        "asm": "3045022100a25cac62fc849ed2e7e75c50465a509ec53540fb05fefc37f7ca2792b3f40264022015ab022d66f967ac0a54a8267a4c4a7c7496a2a17eb7aa44500df4dc1e720fd2[ALL|FORKID] 02f418d6148855a6c83068ba3397048e9fd3a824468f6b39622451a6a58cf8f4a0",
        "hex": "483045022100a25cac62fc849ed2e7e75c50465a509ec53540fb05fefc37f7ca2792b3f40264022015ab022d66f967ac0a54a8267a4c4a7c7496a2a17eb7aa44500df4dc1e720fd2412102f418d6148855a6c83068ba3397048e9fd3a824468f6b39622451a6a58cf8f4a0"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.00100000,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 f2e270cf42acbd1653e014ebfd54294f718db882 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914f2e270cf42acbd1653e014ebfd54294f718db88288ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "1P9FnoAoyxFEPF7HMcdgXCoPFaMXJEMxjV"
        ]
      }
    }, 
    {
      "value": 0.10888220,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 f348714f4956773f6731f190419b2db1e200ca27 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914f348714f4956773f6731f190419b2db1e200ca2788ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "1PBMz1vpLTk1zfd64WF4ewrLFffewmFzLQ"
        ]
      }
    }
  ]
}`

Cannot send BitcoinCash with Ledger NanoS?

**Comment by gre** [comment]
we are working on it @wannabit-booyoun  :)

**Comment by wannabit-booyoun** [comment]
Sounds great, is there an expected date it will be released? Hope it is going to be soon.

**Comment by gre** [comment]
@amougel is working on it right now, so hopefully soon :)

**Comment by gre** [comment]
in v4.13.0, there is an extra option to createPaymentTransactionNew https://github.com/LedgerHQ/ledgerjs/blob/ff92a8df623e7c8e86c8625e0e48c335fca69ff4/packages/hw-app-btc/src/Btc.js#L484
you can basically pass `["abc"]` in case of bitcoin cash

in future we will probably refine this API because there is lot of arguments now ! but it should be good for now

**Comment by wannabit-booyoun** [comment]
Thanks a lot.

**Comment by gre** [comment]
(also the param should be  `["abc"]` not `"abc"` )

**Comment by ayush-techracers** [comment]
Hi @gre , 
Please let me know if you need anything else that I shall share with you, so that you can help me out.
