### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by 7flash** [LedgerHQ/ledgerjs#165]
Following instructions...
![screenshot_2018-06-13_17-39-16](https://user-images.githubusercontent.com/4569866/41358307-c7f1603e-6f30-11e8-8b86-85e08c7ffcfb.png)

**Comment by gre** [comment]
this is using create-dapp ? if not, i guess this is a bug to report to web3-provider-engine

**Comment by 7flash** [comment]
Yes, if there is any way to build any version of template from repository?

**Comment by 7flash** [comment]
Was it fixed?

**Comment by gre** [comment]
I think this is now fixed (version `5.2.0`)
