### ISSUE TITLE
Use Ledger with (non-HTTPS) localhost application

### ISSUE THREAD

**Issue by tinybike** [LedgerHQ/ledgerjs#173]
I want to use ledgerjs with an application (specifically, [Augur](https://github.com/AugurProject/augur)) that is intended to be downloaded and accessed via localhost in the browser.  Since it is localhost, it does not use HTTPS.  (Our feeling is that it isn't practical to ask every user to generate a self-signed SSL certificate and accept it in their browser.)  We are trying to connect from the browser using `comm_u2f.create_async`, which throws the following error in the (Chrome) browser console:

![u2f error](https://user-images.githubusercontent.com/2637020/42137973-5d78260e-7d2a-11e8-808e-1ad7f4ac4b63.png)

It is definitely _possible_ to use hardware wallets via regular-HTTP localhost because Trezor works fine.  [trezor.js](https://github.com/trezor/trezor.js) looks like it passes U2F requests using WebUSB.  Would it be possible for ledgerjs to use WebUSB in the same way?

Note: I'm not sure if this matters, but we are ledgerjs indirectly, through the [ethereumjs-ledger](https://github.com/ethereumjs/ethereumjs-ledger) convenience wrappers.

Note 2: we only tested Trezor-on-http://localhost w/ Chrome so far, assuming it also works in Firefox but haven't actually tried it yet.

**Comment by MicahZoltu** [comment]
I _think_ the reason the Trezor works is because its recommended workflow is to open a pop-up window hosted at https://trezor.com, which then interfaces with the trezor and provides the dapp with the response.  If this is correct, then the same could be done with Ledger.  Something to consider is that this workflow creates a MitM attack vector where the attacker takes over the signing service and presents the hardware device with the wrong transaction to sign.

**Comment by tinybike** [comment]
Just to follow up on @MicahZoltu's comment, this MitM attack vector is not only possible, it appears to have just been executed against wallet.trezor.io: https://blog.trezor.io/psa-phishing-alert-fake-trezor-wallet-website-3bcfdfc3eced

:neutral_face:

**Comment by gre** [comment]
@tinybike to answer your initial question:

- i'm not aware of a way to use U2F in http, it requires https, even for localhost.
- For WebUSB i'm a bit surprised as I thought it always was always requiring https too. Maybe http://localhost is whitelisted?

Today, we have no support for WebUSB but hopefully it should land soon.

> Also, you are (indirectly) using the legacy library, the repository hosts many libraries like `@ledgerhq/hw-transport-u2f` but `"ledgerco"` is no longer maintained.

**Comment by gre** [comment]
Both u2f and webusb requires https so this is not trivial to workaround (unless you use indirect way like the mentioned iframe idea or any extension like metamask)

At the same time it is recommended for crypto websites to use https and is also becoming overall [more and more recommended](https://www.google.fr/amp/s/searchengineland.com/effective-july-2018-googles-chrome-browser-will-mark-non-https-sites-as-not-secure-291623/amp).

For these reasons I assume the ratio priority/complexity to be low enough to close this issue.
Thanks

**Comment by liamzebedee** [comment]
For any future readers, I got this working for a local dApp using [mitmproxy](https://mitmproxy.org/):

`mitmdump -p 443 --mode reverse:http://localhost:3000/`
