### ISSUE TITLE
Unable to create, sign, and broadcast eth transaction on ropsten

### ISSUE THREAD

**Issue by nmajor25** [LedgerHQ/ledgerjs#177]
I am unable to successfully sign and broadcast an eth transaction. My code is below.

Sign transaction code:

`

    const getTransport = () => TransportU2F.create()
    const eth = new AppEth(transport)
       
    const rawTxData = {
      'nonce': '0x01',
      'gasPrice': '0x2cb417800',
      'gasLimit': '0x5208',
      'from': '0x4422D3c22Ec36739713636eca288Ca8ddB0106E9',
      'to': '0x4203b1F04e88C0E8B1b54b0e38065a3d006283D3',
      'value': '0x5af3107a4000',
      'chainId': '3',
      'v': '0x03',
      'r': '0x00',
      's': '0x00'
    }

    const tx = new EthereumTx(rawTxData)

    const result = await eth.signTransaction(
      "44'/60'/0'/2",
      tx.serialize().toString('hex')
    )

    tx.v = Buffer.from(result.v, 'hex')
    tx.r = Buffer.from(result.r, 'hex')
    tx.s = Buffer.from(result.s, 'hex')

    return tx
    
`

Broadcast transaction code: 

`

    const signedTransaction = `0x${signedTx.serialize().toString("hex")}`

    web3.eth.sendSignedTransaction(signedTransaction)
    .on('transactionHash', function(hash) {
      console.log('Transaction hash: ' + hash)
      callback(hash)
    })
    .on('confirmation', function(confirmationNumber, receipt) {
      console.log('Confirmation number: ' + confirmationNumber)
    })
    .on('receipt', function(receipt) {
      console.log('Receipt: ' + receipt)
    })
    .on('error', console.error)

`

The transaction is sent out smoothly, but on ropsten.etherscan.io the transaction comes up as "Sorry, we are unable to locate this Transaction Hash."

Any ideas why this is happening? Any help is much appreciated! I have been stuck on this for days.

Also, are there any full examples out there of creating a raw eth transaction, signing it with the ledger, and broadcasting it to the ethereum network? I am unable to find any in the ledger documentation or anywhere on github.

**Comment by gre** [comment]
everything looks fine to me. i wonder if it is related to the `nonce` , you have set it to 0x01 is it correct ?

**Comment by gre** [comment]
one code we use today for incoming desktop app: https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/helpers/signTransactionForCurrency/ethereum.js which is almost one-one to your code

**Comment by gre** [comment]
Are you still having the problem?
