### ISSUE TITLE
Does signP2SHTransaction work with arbitrary redeem script?

### ISSUE THREAD

**Issue by bodymindarts** [LedgerHQ/ledgerjs#185]
I'm just looking through the code to investigate support for non-standard bitcoin script inputs. The documentation says you should use `signP2SHTransaction` for signing multisig inputs, but as far as I can tell I could pass in any arbitrary redeem script. Is that correct or are there restrictions on the type of redeem script that can be passed in?

**Comment by btchip** [comment]
Any script can be passed

**Comment by bodymindarts** [comment]
Thank you for the information
