### ISSUE TITLE
Testnet address

### ISSUE THREAD

**Issue by Marxpark** [LedgerHQ/ledgerjs#187]
How does one go about getting his testnet address for the nano ledger?

current code:
var BtcLedger = require("@ledgerhq/hw-app-btc")
var Transport = require("@ledgerhq/hw-transport-node-hid")
  ....
    const transport = await Transport.create();
    const btc = new BtcLedger(transport);
    address = await btc.getWalletPublicKey("44'/0'/0'/0")
    address = address.bitcoinAddress.toString('utf8')

this gets me my mainnet address, but i really need my testnet address for development. There doesnt seem to be a network flag anywhere. 

Thanks

**Comment by gre** [comment]
44’/1’/....

1 for testnet according to bip44 spec

https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

**Comment by rllola** [comment]
You might want to have the Bitcoin Testnet app installed on your ledger and the `bitcoinAddress` should give you a testnet one.

Another way (what I am doing for dogecoin) is to use instead the publicKey `address.publicKey` and not `address.bitcoinAddress`. You can then write the code to generate a testnet address from it... or find a lib that do that.

Here my code for DOGE : 
```
const bs58check = require('bs58check')
const RIPEMD160 = require('ripemd160')
const crypto = require('crypto')

function pubkeyToAddress (pubkey, hash=false, redeemScriptHash=false) {
  let pubKeyHash = pubkey

  if (!hash) {
    pubKeyHash = crypto.createHash('sha256').update(pubkey).digest()
    pubKeyHash = new RIPEMD160().update(pubKeyHash).digest()
  }

  // TODO: Testnet parameter
  let networkByte = new Buffer.from('71', 'hex')

  if (redeemScriptHash) {
    networkByte = new Buffer.from('c4', 'hex')
  }

  let temp = Buffer.concat([networkByte, pubKeyHash])

  return bs58check.encode(temp)
}
```

Look for the `networkByte` for Bitcoin and it should work. And also if I am not mistaken the pubKey return is not hash so you will have `hash=false`.

I hope it helps.

**Comment by rllola** [comment]
Actually you might not want to do that if you want to be able to create transaction... It then create the wrong scriptSig from what I get.

**Comment by Marxpark** [comment]
Thanks for your replies. 

I didn't find the BTC testnet app tbh. 
As you said, you have to find your way around with a different lib.

I've managed to get it working with this chunk of code, using Bitcro
` const getBtcAddress = async () => {
     const wantedNetwork = 'testnet';
     const transport = await Transport.create();
     const btc = new AppBtc(transport);
     const result = await btc.getWalletPublicKey("m/44'/0'/0'/0/0");
     const publicKey = Bitcore.PublicKey(result.publicKey);

     const xpub = Bitcore.HDPublicKey({
         network: wantedNetwork,
         depth: "m/44'/0'/0'/0/0".split('/').length,
         parentFingerPrint: new Buffer('00000000', 'hex'),
         childIndex: 0,
         chainCode: result.chainCode,
         publicKey: Bitcore.PublicKey.fromPoint(publicKey.point).toString(),
     });

     console.log("Address from ledger ", result.bitcoinAddress);
     console.log("Testnet addresss ", xpub.publicKey.toAddress(wantedNetwork).toString());
 };`

Maybe it can be of help to you, or anyone else. 

Mind the derivation paths.

**Comment by meriadec** [comment]
To be able to see BTC Testnet app you have to enable dev mode in the Live app

![2018-07-31_590x103](https://user-images.githubusercontent.com/315259/43452449-c2c2c132-94b7-11e8-9508-b2be33bb41b1.png)

**Comment by rllola** [comment]
@meriadec Does there is any difference when signing using the testnet app and using the mainnet app ?

I tried to sign for testnet using dogecoin app but I got an error. Is it because there is a difference or because I made a mistake ?

**Comment by gre** [comment]
testnet only works for BTC. we don't have any other testnet support today.
