### ISSUE TITLE
Crowdin: prefer using locale instead of two_letter_code

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledgerjs#196]
in crowdin:

<img width="669" alt="capture d ecran 2018-07-26 a 16 04 33" src="https://user-images.githubusercontent.com/211411/43267215-a4243350-90ed-11e8-9662-0053b3ec5944.png">

because we have both cn-ZH and cn-TW

need to move to another format but first need to support it properly.

we probably need to have in the languages list both CN (simplified, traditional) like it's usual to do, but i'm not sure how we'll handle this in terme of lang detection. we'll have to test

**Comment by meriadec** [comment]
是

**Comment by gre** [comment]
好的

**Comment by gre** [comment]
wrong repo XD
