### ISSUE TITLE
Cannot require @ledgerhq/hw-transport-node-hid because of type error

### ISSUE THREAD

**Issue by bodymindarts** [LedgerHQ/ledgerjs#197]
I'm on mac Os 10.13.6 using node 10.6.0 trying to add `hw-transport-node-hid`

When requiring the package I get the following issue:
```
    TypeError: Cannot redefine property: configDescriptor
        at Function.defineProperty (<anonymous>)

      4 | var Jest = require("@glennsl/bs-jest/src/jest.js");
      5 | var HwAppBtc = require("@ledgerhq/hw-app-btc");
    > 6 | var HwTransportNodeHid = require("@ledgerhq/hw-transport-node-hid");
      7 |
      8 | var TransportHid = /* module */[];
      9 |

      at Object.<anonymous> (node_modules/usb/usb.js:47:8)
      at Object.<anonymous> (node_modules/@ledgerhq/hw-transport-node-hid/lib/listenDevices.js:19:12)
      at Object.<anonymous> (node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:55:23)
      at Object.<anonymous> (__tests__/ffi/Ledger_test.bs.js:6:26)
```

The require fails during execution of [this](https://github.com/tessel/node-usb/blob/master/usb.js#L47-L51) code in the [node-usb](https://github.com/tessel/node-usb) package. Can someone help me figure out whats going on?

**Comment by bodymindarts** [comment]
Okay the issue is that I'm importing `@ledgerhq/hw-transport-node-hid` (for testing) and `@ledgerhq/hw-transport-u2f` at the same time so the usb package gets loaded twice.

Any ideas on how to conditionally include `@ledgerhq/hw-transport-u2f` only when not executing test code?

**Comment by gre** [comment]
why do you import both node-hid and u2f at same time 🤔  

so in such case, usually what you can do is making your project explicitely depending on usb and it should help npm/yarn resolving the dependencies. it force a dedup I think

**Comment by bodymindarts** [comment]
I need u2f because I'm deploying an SPA, I need node-hid to run unit-tests. I've tried depending explicitly on usb but that doesn't seem to work.

**Comment by bodymindarts** [comment]
Or is there a way to run tests via `u2f` without depending on a browser?

**Comment by MortalKastor** [comment]
> Okay the issue is that I'm importing `@ledgerhq/hw-transport-node-hid` (for testing) and `@ledgerhq/hw-transport-u2f` at the same time so the usb package gets loaded twice.

That seems unlikely as I see no dependance on `usb` in `@ledgerhq/hw-transport-u2f`.

Did you manage to get each package to work in your project on their own (ie `node-hid` without `u2f` and vice versa)?

> Or is there a way to run tests via `u2f` without depending on a browser?

I assume that a u2f API polyfill in node would do the trick.

**Comment by bodymindarts** [comment]
Okay after further investigation you are right it has nothing to do with `@ledgerhq/hw-transport-u2f` rather the test runner `jest` seems to be reloading the code when it is in watcher mode. So in actual fact it isn't a duplication issue, it just reloads the same package when rerunning the test.... weird.

**Comment by comountainclimber** [comment]
@bodymindarts Im running into the exact same issue... did you ever find a workaround?

**Comment by bodymindarts** [comment]
@comountainclimber no unfortunately I didn't find an answer to the issue with `jest`

**Comment by gre** [comment]
i'm facing the same issue with Jest at the moment. this reproduces as soon as you have two test files and you use `--runInBand` or if you start to have at least 4 test files.

No solution found so far

**Comment by elkesrio** [comment]
I'm facing the same issue, using `jest`. Any updates?

**Comment by Sajjon** [comment]
I have the same problem, `jest`, mono-repo with many packages Any solutions so far?

**Comment by Sajjon** [comment]
@gre @elkesrio @comountainclimber @bodymindarts I solved it by switching over to using [_dynamic imports_](https://mariusschulz.com/blog/dynamic-import-expressions-in-typescript), like so:

```typescript

export type BasicLedgerTransport = Readonly<{
	close: () => Promise<void>
	send: (
		cla: number,
		ins: number,
		p1: number,
		p2: number,
		data?: Buffer,
		statusList?: ReadonlyArray<number>,
	) => Promise<Buffer>
}>


const basicLedgerTransport: BasicLedgerTransport = await import(
		'@ledgerhq/hw-transport-node-hid'
	).then(
		async (module): Promise<BasicLedgerTransport> => {
			const TransportNodeHid = module.default

			return await TransportNodeHid.create(
				input?.deviceConnectionTimeout,
				input?.deviceConnectionTimeout,
			)
		},
	)
```

N.B. that I declare a "basic" type for just the methods on `TransportNodeHid` I need above, I call it `BasicLedgerTransport`.

**Comment by gre** [comment]
we're in process of migrating to TypeScript, it should help on the matter 🙏 
#596
