### ISSUE TITLE
Ledger Nano Freezes on Ethereum Signing

### ISSUE THREAD

**Issue by nickfogle** [LedgerHQ/ledgerjs#198]
When attempting to sign a transaction with a non-hardened purpose derivation, the device freezes after the user clicks to confirm the transaction. The device stays frozen until unplugged and reconnected. I'm able to dupe this behavior 100% of the time using different devices and different firmware versions (1.3.1 & 1.4.2). In the following two code samples, the first will cause the device to freeze while the second will not. Notice that the only difference is derivation hardening.

Freezes device upon signing. 
```javascript
import Eth from "@ledgerhq/hw-app-eth";

export default async transport => {
  const eth = new Eth(transport);
  const result = await eth.signTransaction(
    "44'/60/0/0/0",
    "e8018504e3b292008252089428ee52a8f3d6e5d15f8b131996950d7f296c7952872bd72a2487400080"
  );
  return result;
};
```

Signing works fine.
```javascript
import Eth from "@ledgerhq/hw-app-eth";

export default async transport => {
  const eth = new Eth(transport);
  const result = await eth.signTransaction(
    "44'/60'/0/0/0",
    "e8018504e3b292008252089428ee52a8f3d6e5d15f8b131996950d7f296c7952872bd72a2487400080"
  );
  return result;
};
```

Would it be possible to support signing of Non-hardended paths in the future?

**Comment by amougel** [comment]
@btchip  I think this behaviour is intended? Maybe not the freeze but the impossibility of signing non hardened purposes?

**Comment by nickfogle** [comment]
For what it's worth, I'm able to sign non-hardened purpose paths using Ledger's BTC library, so I'm wondering if this is a bug or more of a prescriptive decision to block signing of non-hardened ethereum paths.

**Comment by btchip** [comment]
Yes, it's deliberate - ultimately this will also be removed from BTC (at least one hardened path will be necessary)
