### ISSUE TITLE
signTransaction_async issue

### ISSUE THREAD

**Issue by Yerontour** [LedgerHQ/ledgerjs#20]
I created a raw transaction based on the example, but I get a different v, r and s values compared with MyEtherWallet.com or my private Ethereum node.

Here the full description on StackExchange: https://ethereum.stackexchange.com/questions/28392/ledger-wallet-node-js-api-signtransaction-async-implementation-issue

**Comment by gre** [comment]
see https://github.com/LedgerHQ/ledgerjs/issues/43#issuecomment-366984725
