### ISSUE TITLE
Add more supported derivations for web3-subprovider

### ISSUE THREAD

**Issue by qmn1711** [LedgerHQ/ledgerjs#200]
For now @ledgerjs/web3-subprovider support only `44'/60'/x'/n` pattern.
**But in Ledger Live they're using `m/44'/60'/0'/0`, so please support this derivation in @ledgerjs/web3-subprovider.**

p/s: Could @ledgerjs/web3-subprovider accept a lot of derivations like myetherwallet.com doing?

**Comment by pointtoken** [comment]
Indeed, I think this broken the implementation on airswap, as I tried to use my Ledger (initialized with Ledger Live) on airswap and it couldn't find my address.

**Comment by pointtoken** [comment]
I'm seeing this break all earlier Ledger implementations -- for example, if I use a Ledger on IDEX it can't find the address of my current ETH address.  Something is broken...

**Comment by amougel** [comment]
Changing the current implementation of account listing will either be a breaking change or really messy. I am thinking of replacing current `path`, `acountsOffset` and `accountsLength` by a list of paths [SubproviderOptions] to allow for more flexibility. (https://github.com/LedgerHQ/ledgerjs/blob/86d81b6d4c50e6b6a7fcdba550fa87f88e946b1c/packages/web3-subprovider/src/index.js#L32-L43)

@gre WDYT?

**Comment by TimDaub** [comment]
I'm facing the same issue. Send some ERC721 to an address of m/44'/60'/0'/0 and now I cannot retrieve it with ledgerjs.

**Comment by milonite** [comment]
Same problem. There's some plan to support different paths?  I still get 

For now @ledgerjs/web3-subprovider support only 44'/60'/x'/n pattern.
But in Ledger Live they're using m/44'/60'/0'/0/0, so please support this derivation in @ledgerjs/web3-subprovider.
