### ISSUE TITLE
Could not initialize libusb. Check that your system has a usb controller.

### ISSUE THREAD

**Issue by DalderupMaurice** [LedgerHQ/ledgerjs#209]
Hey

Migrating from v4.18.0 to 4.22.0, we get the following error on our CI environment (CircleCI) 
`Could not initialize libusb. Check that your system has a usb controller.`
It's caused because the CI obviously doesn't have a usb controller, is there any way to avoid this error?

**Comment by DalderupMaurice** [comment]
Any update on this?

**Comment by mhuggins** [comment]
It looks like this issue [was fixed](https://github.com/tessel/node-usb/pull/260) in usb@1.3.3.  This package currently requires usb@^1.3.2.

**Comment by mhuggins** [comment]
I thought I had managed to fix this by:

1. Reinstalling this package in order for sub-dependencies to update:

    ```
    $ yarn remove @ledgerhq/hw-transport-node-hid
    $ yarn add @ledgerhq/hw-transport-node-hid@4.22.0
   ```

2. Adding an extra step to our CircleCI build config:

    ```
    $ sudo apt-get -y install libudev-dev libusb-1.0-0-dev
    ```

However, I'm still getting the same error in CI.  Interestingly, I'm getting it in fewer spots.

**Comment by gre** [comment]
Closing because not related to this library.
But I agree node-usb tends to be complex to compile on some system. On our side we're having trouble compile it for node 8.12.0 and we'll all downgraded to 8.9.4
