### ISSUE TITLE
Fetch Receiving Transactions from Blockchain for Imported Address using Ledger API. 

### ISSUE THREAD

**Issue by nitindigixhub** [LedgerHQ/ledgerjs#236]
Hello,

We are integrating the Ledger Device with our Exchange Application and at the moment we are able to import all the data for Bitcoin and other cryptocurrencies in related which open with Bitcoin App.

After exporting the address in bulk eg. 2000 address we want to create a function or a subscription with ledger API to intimate us whenever any transaction happens on their address for the respective cryptocurrencies.

Please let me know if any such possibilities are available in the existing ledger API.

I will look forward for an immediate response from the community to help on understanding the above issue.

**Comment by plondon** [comment]
What you need is a websocket: https://www.blockchain.com/api/api_websocket.

Also, instead of 'exporting the address in bulk', can you just extract the xpub?
