### ISSUE TITLE
Signing bch multi-signing transaction failed

### ISSUE THREAD

**Issue by Chappell-C** [LedgerHQ/ledgerjs#237]
I have two cold wallets：ledger and trezor , their mnemonic is the same.

When I am doing multi-signature transactions，I have settings coinType as 'abc'，but the signature results of the two hardware are different.

I sent trizor's signature message to the chain and confirmed it successfully. This means that the ledger signature with the same mnemonic is wrong.I don't know where the problem is. Or the ledger can't sign the multi-signature of bch. 

Note：1. The data of the two hardware signatures is exactly the same；
            2. The calculated output script is also the same；

Ledger multi-sign parameters are mainly output scripts and path, since the trezor sends the transaction successfully, it can be determined that the two data are correct.

![image](https://user-images.githubusercontent.com/31213168/47640696-22819200-db9f-11e8-9aad-8d5db6b482d3.png)

It is wrong to get the signature after calling this method. I don't understand why, I need your help, thank you.

**Comment by shinandi** [comment]
I’m dealing with the same problem as you.
