### ISSUE TITLE
hw-transport-node-hid  on React

### ISSUE THREAD

**Issue by milonite** [LedgerHQ/ledgerjs#242]
When i'm trying to use on my react application (create-react-app) 

`import TransportNodeJs from '@ledgerhq/hw-transport-node-hid'
`
i get this error: 

`Module not found: Can't resolve 'aws-sdk' in 'C:\Users\TAACOMI8\Desktop\MINTING APPLICATION\minting-tool\node_modules\usb\node_modules\node-pre-gyp\lib'`

**Comment by meriadec** [comment]
hw-transport-node-hid is meant to be run on Node.js, you probably want to use hw-transport-u2f for browser usage.

**Comment by milonite** [comment]
> hw-transport-node-hid is meant to be run on Node.js, you probably want to use hw-transport-u2f for browser usage.

Hi, it's meant to be use in an electron application that dosn't support u2f

**Comment by meriadec** [comment]
So you can explore here: https://github.com/LedgerHQ/ledger-live-desktop, which is an electron app using node-hid as well.

**Comment by gre** [comment]
I don't see how the error relate to ledger lib. It's mentioning aws-sdk which we don't even depends on.

Hope you can figure it out. Open an new issue if you have more precision or a bug.

**Comment by gre** [comment]
Or maybe it's a bug in node-usb so maybe to be raised in node-usb

**Comment by milonite** [comment]
@gre  seems so: https://github.com/tessel/node-usb/issues/215  can be fixed editing the webpack.config but into create-react-app I'm not sure it's possibile
