### ISSUE TITLE
@ledgerhq/hw-transport-node-hid fails in tests (Jest)

### ISSUE THREAD

**Issue by DalderupMaurice** [LedgerHQ/ledgerjs#250]
While running tests with Jest, I get the following error:
```
    Cannot find module
    \\?\D:\<path_node_modules>\node_modules\usb\src\binding\usb_bindings.node

      Error: Kan opgegeven module niet vinden.
      \\?\D:\<path_node_modules>\node_modules\usb\src\binding\usb_bindings.node
```
This error was introduced since 4.18.0 and is present in all version from 4.18.0 until the most recent one (4.23.0)

**Comment by kartojal** [comment]
Same error here, while importing the module:
```
Error: Cannot find module '/home/davidracero/repos/profit-sender/node_modules/usb/src/binding/usb_bindings.node'
```

**Comment by kartojal** [comment]
Following these steps i could pass the error you describe @DalderupMaurice 
https://github.com/LedgerHQ/ledgerjs/issues/209#issuecomment-424048925

**Comment by gre** [comment]
https://github.com/LedgerHQ/ledger-live-common/tree/master/cli

this package depends on node-hid and without a problem to run tests with Jest. maybe check on latest version of packages.
