### ISSUE TITLE
Support eth_signTypedData ?

### ISSUE THREAD

**Issue by digitaldonkey** [LedgerHQ/ledgerjs#251]
Does ledgerhq/web3-subprovider support eth_signTypedData?

**Comment by aydnep** [comment]
@digitaldonkey i'm not sure about `eth_signTypedData` but recently i had issue with `web3.eth.sign`. To solve this i just add next:
```
      const ledgerProvider = createLedgerSubprovider(() => TransportU2F.create(), options);
      ledgerProvider.signMessage = ledgerProvider.signPersonalMessage;
```
