### ISSUE TITLE
XRP Multisig Transaction: Invalid Signature

### ISSUE THREAD

**Issue by ayush-techracers** [LedgerHQ/ledgerjs#252]
Hi,

I'm trying to sign the XRP multi-sig transaction hex using `ledgerjs`, when I keep `SigningPublicKey` blank it throws an error. This is a recommendation from Ripple's documentation, you can go to ripple's documentation: 
https://developers.ripple.com/multi-signing.html#sending-multi-signed-transactions 
The second point says: "The transaction must include the SigningPubKey field as an empty string."

So I keep the `SigningPubKey` blank before signing a transaction using the ledger. But ledger does not accept that.

On the other hand, in `ledgerjs` code:
https://github.com/LedgerHQ/ledger-app-xrp/blob/master/src/xrpParse.c#L160 
It seems that the `SigningPubKey` is required. When I send the `SigningPublicKey` with transaction hex while signing, It gives me the signature, but it is wrong. Because when I try to broadcast the transaction with that signature it gives me the following error: `Invalid signature on account rxxxxxxxx...`

Here is the code snippet I'm using:

```js
const TransportHid = require("@ledgerhq/hw-transport-node-hid").default;
const Xrp = require("@ledgerhq/hw-app-xrp").default;
import Bin from 'ripple-binary-codec';
TransportHid.create()
  .then(async transport => {
    var signTxXrp = async (
      path
    ) => {
      const xrp = new Xrp(transport);
      let tmpjson = {
          "Account": "rh9GeZwoLxEaJTC9VkTBenLucfKMigNZPD",
          "Fee": "200",
          "TransactionType": "Payment",
          "Sequence": 3,
          "Destination": "rnXnbo6pDDhfzYgwjUch4AQNpSQD7guxW1",
          "Amount": {
            "currency": "XRP",
            "issuer": "r92jUU3aJD586CYTXCNkkNeDwj7TLfAAyq",
            "value": "5000"
          }
      };
      
      const addrObj = await getAddress(path);
      tmpjson.SigningPubKey = "";
      const signit = Bin.encode(tmpjson);
      const signatures = await xrp
        .signTransaction(path, signit)
        .catch(err => console.log("Error inside p2sh", err));

      tmpjson.Signers = [];
      let signObj = {
        Signer:{ 
            SigningPubKey: addrObj.publicKey.toUpperCase(),
            TxnSignature: signatures.toUpperCase(),
            Account: addrObj.address 
        } 
      };
      tmpjson.Signers.push(signObj);
      const signedTransaction = Bin.encode(tmpjson);
      return signedTransaction;
    };

    var getAddress = async (path) => {
      const xrp = new Xrp(transport);
      const accountObj = await xrp
        .getAddress(path)
        .catch(err => console.log("Error inside p2sh", err));
      return accountObj;
    };
    signTxXrp(
      "44'/144'/0'/0/4"
    );
  })
  .catch(err => console.log(err));
```

Please let me know if my work is futile and Ledgerjs is not yet compatible with XRP multisig.

**Comment by y0ke** [comment]
duplicate of #175 
Empty string of `SigningPubKey` end up changing a hash that Ledger sign and Empty string `SigningPubKey` must be specified.
So, as long as Ledger doesn't allow a black `SigningPubKey`, Ledger cannot sign a ripple multisign tx

**Comment by ayush-techracers** [comment]
Thanks @y0ke , I am closing the issue. Until ledger firmware is updated.
