### ISSUE TITLE
@ledgerhq/hw-transport-u2f: Bad interaction between CSP & non-compatible browser

### ISSUE THREAD

**Issue by MisterTicot** [LedgerHQ/ledgerjs#254]
**Issue:**

When loading Ledger transport library into a non-compatible browser with strict Content-Security-Policy, the iframe generated by the library displays on the page with an error message. You can check it at [https://cosmic.link] by selecting `Ledger Wallet` as authentication method. I got that error both on Firefox (Ubuntu 18.10) and Android Chrome.

I assume it is related to the strict Content-Security-Policy (`script-src: 'self';`) as it triggers an error message telling so. This error would not appear before I did set this policy rule.

I hope this could get solved quickly as it kind of mess with the layout and give a negative image of a system that user expect to be secure (hence bug-free).

*Edit:* On my website this have been partially fixed so now you would only see the frame blinking quickly.

**Solution:**

Adding `chrome-extension` into my policy rule may be a quick fix but is not satisfactory (that's a hack).

The proper solution would be to remove that frame once a non-compatible browser is detected. This would be cleaner at every level.

**Comment by MisterTicot** [comment]
The error is due to the fact that this iframe is normally made invisible because of `style="display:none;"`. However, under my strict CSP rules CSS inlining is forbidden - so the frame shows up.

This could get partially fixed by adding the HTML5 attribute `hidden` to the iframe. My experience is that attribute is not always handled perfectly, as it can be overridden by a `display` CSS definition - but in our case this is rather unlikely.

I would recommend to add the `hidden` attribute and maybe keep the `style="display:none;"` just to be sure. I would also consider destroying the iframe on non-compatible browsers if it doesn't serve any further purpose.

**Comment by MisterTicot** [comment]
I tried to fix in into my own library wrapper by removing the frame after failure but you would still see the frame blinking. I thing I'll try to set iframe hidden attribute just after transport connection.

**Temporary Fix:** https://github.com/cosmic-plus/node-ledger-wallet/commit/3981dab5d1d28d0c34a40344a1228ca93d07864b#diff-5da93726c6b0fe6dfa4d1b76cdc3767dL109

**Comment by gre** [comment]
I'm afraid the problem is linked to U2F and there is no easy fix for it but to migrate to WebUSB / hope WebHID is going to get stable and supported everywhere.
U2F have no concept of device and no connection lifecycle.
In WebUSB/WebHID you will take the device connection and it will not be possible to open it in another tab / app.
