### ISSUE TITLE
BTC Transaction more utxos

### ISSUE THREAD

**Issue by garysen** [LedgerHQ/ledgerjs#255]
Sometimes there is an extreme case, when a transaction (BTC) contains
multiple UTXOS (say 500 UTXOS), the hardware needs a long time to complete the
signature, and sometimes even cannot be signed successfully. What is the
optimization scheme? Thanks!

**Comment by gre** [comment]
what we will do is introducing a callback to get progress events so you can have an UI that shows this to the user. We plan to work on that soon.
