### ISSUE TITLE
regeneratorRuntime not defined error in new xrp app 

### ISSUE THREAD

**Issue by Marxpark** [LedgerHQ/ledgerjs#258]
New xrp app doesn't work (at least for me). Constantly throws error regeneration runtime is not defined:

```
./node_modules/@ledgerhq/hw-app-xrp/lib/Xrp.js:53
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(path, display, chainCode, ed25519) {
                                                 ^

ReferenceError: regeneratorRuntime is not defined
    at ./node_modules/@ledgerhq/hw-app-xrp/lib/Xrp.js:53:50
    at ./node_modules/@ledgerhq/hw-app-xrp/lib/Xrp.js:106:6
    at Object.<anonymous> (./node_modules/@ledgerhq/hw-app-xrp/lib/Xrp.js:290:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```
if i add `const regeneratorRuntime = require("regenerator-runtime");` in the lib/xrp.js, it starts working normally.

**Comment by meriadec** [comment]
looks like you need to add babel-polyfill

**Comment by Marxpark** [comment]
Yeah, google said that in a couple of posts, but its not the appropriate solution. If it's a known requirement, it should be in the dependancies? And in a way, it is, because if i add the require statement, then everything works fine. The last version of the app (4.25) works perfectly fine out of the box, not having to install any of babel deps.
And even when i installed babel polyfill, it still didnt work for me...

**Comment by meriadec** [comment]
it originated here https://github.com/LedgerHQ/ledgerjs/pull/228
I agree, it's a pain to have this particularity. Should be temporary until moving to babel@7

**Comment by Marxpark** [comment]
Googled the s*** out of the error, didnt find that thread. Thanks!

**Comment by Moejoe90** [comment]
I think this problem should be still open as moving to babel@7 didn't solve it

**Comment by MicahZoltu** [comment]
I am getting this with latest release `0.48.0` in a very simple project (almost no other dependencies besides ledgerhq stuff).

**Comment by MicahZoltu** [comment]
The recommended solution of `import "babel-polyfill"` doesn't work, just results in `Cannot find module 'babel-polyfill'`.

**Comment by meriadec** [comment]
`npm i babel-polyfill`
