### ISSUE TITLE
EOS App API

### ISSUE THREAD

**Issue by rahilzebpay** [LedgerHQ/ledgerjs#259]
Does this library expose Eos app API?

**Comment by Chappell-C** [comment]
@ledgerhq/hw-app-eth | Ethereum Application API
@ledgerhq/hw-app-btc | Bitcoin Application API
@ledgerhq/hw-app-xrp | Ripple Application API
@ledgerhq/hw-app-str | Stellar Application API
@ledgerhq/hw-app-ada | Cardano ADA Application API


Is EOS using one of these current apis?  Or does it have its own api not yet public?

**Comment by rahilzebpay** [comment]
Nope it doesn't

There is one created by altshiftdev here. 
https://github.com/altShiftDev/eosledgerjs

But it definitely doesn't work with browser transport. 
Throws this error `CLA_NOT_SUPPORTED`. 
Even if I can get this to work it would be great.

**Comment by amirsimhi** [comment]
Are you planning to implement EOS api soon?

**Comment by gre** [comment]
please contact EOS devs / contribute to https://github.com/altShiftDev/eosledgerjs 

we're not planning to add a library in ledgerjs itself as the idea is that third party is developing the EOS app and the starter kits / libs that come with it (so it's decentralized). we're happy to reference it in our main README if someone make a working implementation.
