### ISSUE TITLE
CLA_NOT_SUPPORTED

### ISSUE THREAD

**Issue by rahil471** [LedgerHQ/ledgerjs#261]
Hello team, 

I'm facing this error while trying to ledger nano s with ledgerjs

*Ledger device: CLA_NOT_SUPPORTED (0x6e00)*

**Comment by e-maximus** [comment]
I get the same error when I try to switch to another application. 
Ledger team, could you explain where this error comes from? Could you provide more information about device errors?

**Comment by gre** [comment]
this usually means you use a call that is not supported to where you are on the device. Like you try to get bitcoin address while you're still on the dashboard on the device.

**Comment by gre** [comment]
without extra code to reproduce that and more detail, we'll close the issue
