### ISSUE TITLE
Ethereum getAddress_async Failure

### ISSUE THREAD

**Issue by matthewdowney** [LedgerHQ/ledgerjs#27]
I'm trying to grab an Ethereum address.

```
new ledger.eth(comm).getAddress_async("m/0'", true, true).then(function (result) {
    // ...
}).fail(function (error) {
    // ...
});
```

But I keep getting `Invalid status 6804`. I modified the `ledgerUnwrap` function in `ledger-comm-node.js` to print what it's unwrapping:
```
	var ledgerUnwrap = function(channel, data, packetSize) {
	    console.log("Unwrapping " + JSON.stringify([channel, data, packetSize]));
            // ...
```

Retrying the call every second, my log output is

```
Unwrapping [257,{"type":"Buffer","data":[1,1,5,0,0,0,2,104,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},64]
"Invalid status 6804"
Unwrapping [257,{"type":"Buffer","data":[1,1,5,0,0,0,2,103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},64]
"Invalid status 6700"
Unwrapping [257,{"type":"Buffer","data":[1,1,5,0,0,0,2,104,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},64]
"Invalid status 6804"
Unwrapping [257,{"type":"Buffer","data":[1,1,5,0,0,0,2,103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},64]
"Invalid status 6700"
```

The `6700`s are when the ledger is unlocked but not in the Ethereum app, the `6804`s are when it's unlocked and the app is open. Browser & contract support are off, I'm running this from node locally, and when I use the same comm to query bitcoin public keys I have no problem.

Any ideas?

**Comment by gre** [comment]
there are new version of the libraries, you might especially try the new web3-subprovider for ethereum.
the issue is old and the odds are that it is probably fixed. feel free to recreate a new issue.

**Comment by matthewdowney** [comment]
Thanks for the heads up.
