### ISSUE TITLE
Inconsistent derivation  between web3-subprovider and Ledger Live application

### ISSUE THREAD

**Issue by dimitrykislichenko** [LedgerHQ/ledgerjs#273]
Ledger Live application uses 44'/60'/0'/0/0 derivation, but web3-subprovider allows only to use something like 44'/60'/0'/0, which as the result generates different address.

**Comment by gre** [comment]
the derivation used should probably be externalized. ledger live support different derivation schemes, not only 44'/60'/0'/0/0 but still support  44'/60'/0'/0 (which was the legacy)
