### ISSUE TITLE
Can I get LTC native messages using ledger's API?

### ISSUE THREAD

**Issue by Chappell-C** [LedgerHQ/ledgerjs#276]
When I use btc testnet, I can get the transaction message through this： "https://api.ledgerwallet.com/blockchain/v2/btc_testnet/transactions/fdf28b29deb4d4893f7c414362236bbe968851fbd946fe535bdf0accf9260df8/hex"

Whether litecoin（or litecoin testnet） also has the same api.
I failed with the link below：
https://api.ledgerwallet.com/blockchain/v2/litecoin_test/transactions/fdf28b29deb4d4893f7c414362236bbe968851fbd946fe535bdf0accf9260df8/hex

**Comment by gre** [comment]
our explorer API is not open source and we do not provide support for it. also unrelated to ledgerjs.
