### ISSUE TITLE
Transaction signing issue u2f

### ISSUE THREAD

**Issue by willdn** [LedgerHQ/ledgerjs#29]
I get this error `{errorCode: 1, errorMessage: "device status code: -3"}` when trying to sign an ark transaction with a Nano S.

``` javascript
const ledgerArk = new LedgerArk(this.$store.getters.app.ledgerComm)
const amount = 1 * Math.pow(8, 10)

let tx = arkjs.transaction.createTransaction(
  'Valid address',
  amount,
  null,
  '',
  null
)
delete tx.signature
tx.senderId = this.$store.getters.wallet.address
tx.senderPublicKey = this.$store.getters.wallet.publicKey

const slip44 = this.$store.getters.networkType.slip44
const rawTx = arkjs.crypto.getBytes(tx, true, true).toString('hex')

ledgerArk.signTransaction_async(`44'/${slip44}'/0'/0/0`, rawTx)
  .then((result) => {
    console.log(result)
  })
  .fail((error) => {
    console.log('Ledger error : ', error)
  })
```

```javascript
// console.log(tx)
{
  "type": 0,
  "amount": 1073741824,
  "fee": 10000000,
  "recipientId": "Valid recipient address",
  "timestamp": 21264018,
  "asset": {},
  "senderPublicKey": "Valid sender public key",
  "id": "b664b25cfec17dd88a9d9a0c90c1cccdaa071a4e8d59ed01e4e2633c838c957e",
  "senderId": "Valid sender address"
}
```

Browser support is on. LedgerArk is available [here](https://github.com/ArkEcosystem/ark-desktop/blob/master/LedgerArk.js). I get `ledgerComm` from `ledger.comm_u2f.create_async()`, I have no trouble to get addresses, just signing.

**Comment by gre** [comment]
could you try again? we have upgraded some libraries, especially depending on u2f-api

**Comment by wannabit-jayb** [comment]
@willdn 
I am also having this problem. Did you solve this issue? If you did, could you tell me how?

@gre 
Are you aware of this issue, and you fixed it starting from what version?

**Comment by gre** [comment]
I wasn't aware that the code actually comes from an external library "LedgerArk". therefore i'm not sure if the bug is here or in the LedgerArk library, as it's just using the "transport", the way to send APDU commands over U2F: and it is correctly working. so my bets are that it's a bug in LedgerArk ?

probably need to track these issues: https://github.com/ArkEcosystem/ark-desktop/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ledger

**Comment by numero41** [comment]
Guys can you link your issues in any way to those?
https://github.com/CityOfZion/neon-wallet/issues/524

**Comment by gre** [comment]
closing if for now as LedgerArk is not maintained here, please refer to the repository where it is maintained
