### ISSUE TITLE
Ledger software does not support signing segwit inputs

### ISSUE THREAD

**Issue by johnoliverdriscoll** [LedgerHQ/ledgerjs#30]
What is status of implementation?

**Comment by matthewdowney** [comment]
I'm curious if your experience is the same as mine, where a call to `btc.splitTransaction(...)` returns an object with inputs `[]`? What's happening for me is I'm splitting a transaction with segwit inputs nested in p2sh format... so theoretically backwards compatible, and then the ledger gives a status `0x6A80`.

Is this what you're seeing too?

**Comment by johnoliverdriscoll** [comment]
> Is this what you're seeing too?

Based on the code, it appears the high level communications library is missing some necessary boiler plate code before the device will sign using segwit v0.

**Comment by matthewdowney** [comment]
I'm writing the code right now for splitting the segwit inputs to allow signing of the backwards compatible segwit transactions (p2wpkh-p2sh), but I'm not working on the implementation for native segwit. If you're trying to do the same thing that I'm fixing, I'll post my code when it's done.

**Comment by johnoliverdriscoll** [comment]
Any update @btchip ?

**Comment by johnoliverdriscoll** [comment]
Any update @btchip ?

**Comment by btchip** [comment]
This is being worked on, ETA coming weeks if nothing gets in the middle.

**Comment by Xekyo** [comment]
@btchip: Hey, congrats on the funding! I was wondering whether you had an update?

**Comment by gre** [comment]
this has been implemented by @amougel and is available in v2.2.0.
please test it and feel free to create a new github issue if there is a problem.
Thanks
