### ISSUE TITLE
Ledger sign Xrp SignerListSet transaction error

### ISSUE THREAD

**Issue by Chappell-C** [LedgerHQ/ledgerjs#301]
const txJSON = {
            "Flags": 0,
            "TransactionType": "SignerListSet",
            "Account": "rHY7NsP6nrwRpo7knuq2c5ddZNHuU6D5tm",
            "Fee": "10000",
            "LastLedgerSequence":17290230,
            "Sequence":5,
            "SignerQuorum": 2,
            "SignerEntries": [
                {
                    "SignerEntry": {
                        "Account": "rGt28kqEQCpvk6KWQhbGty8xJfVgjax8ML",
                        "SignerWeight": 1
                    }
                },
                {
                    "SignerEntry": {
                        "Account": "rna2WjvYwb6ryA4KsXTfcpq7uqkyNxXZnM",
                        "SignerWeight": 1
                    }
                }
            ],
            "SigningPubKey": "02BE983F6D591B50434FC68993994FA381F3B63E07F1033A3DBCD37C7E790B7058"
        };

const rawTxHex = Bin.encode(txJSON);
        const transport = await TransportU2F.create();
        const xrp = new Xrp(transport);
        const signature = await xrp.signTransaction("44'/144'/0'/0/0", rawTxHex);

When I use ledger to sign a SignerListSet transaction，Always told that the parameter is invalid（Invalid data received (0x6a80)）.  Above is my request parameters and request method，Is it because some parameters are wrong?

Looking forward to your reply

**Comment by gre** [comment]
@btchip

**Comment by Chappell-C** [comment]
This field reports the same error whether or not there is a SigningPubKey.

**Comment by Chappell-C** [comment]
const txJSON = {
            "TransactionType": "AccountSet",
            "Account" : "rHY7NsP6nrwRpo7knuq2c5ddZNHuU6D5tm",
            "Fee": "12",
            "Sequence": 5,
            "SetFlag": 4,
        }


I think there may be a common problem,I returned the same error when I did the above.

At the moment, I only succeeded in signing a single sign trade.Below are the parameters of my single sign.
 const json = {
            "TransactionType":"Payment",
            "Account":"rHY7NsP6nrwRpo7knuq2c5ddZNHuU6D5tm",
            "Destination":"rnF28G6pWfRAUU7wf3UwPujYR9aF6NTQBw",
            "Amount":"1000000",
            "Flags":2147483648,
            "DestinationTag":1,
            "Fee":"2000000",
            "Sequence":2,
            "LastLedgerSequence":17261169,
            "SigningPubKey": "02BE983F6D591B50434FC68993994FA381F3B63E07F1033A3DBCD37C7E790B7058"
        };

**Comment by Chappell-C** [comment]
I may have used the API incorrectly.When I use Ledger Data Formats，My parameter is：
const txJSON = {
            "Flags": 0,
            "LedgerEntryType": "SignerList",
            "SignerEntries": [
                {
                    "SignerEntry": {
                        "Account": "rGt28kqEQCpvk6KWQhbGty8xJfVgjax8ML",
                        "SignerWeight": 1
                    }
                },
                {
                    "SignerEntry": {
                        "Account": "rna2WjvYwb6ryA4KsXTfcpq7uqkyNxXZnM",
                        "SignerWeight": 1
                    }
                },
            ],
            "SignerListID": 0,
            "SignerQuorum": 2,
        }

There are two parameters, I don't understand.They are “OwnerNode” and “ index”.

There are two more parameters, because I am doing this for the first time, so I don't know what value to give.They are “ PreviousTxnID” and “ PreviousTxnLgrSeq”.

I didn’t pass these values in the end, I still got ‘Invalid data received (0x6a80)’.

![image](https://user-images.githubusercontent.com/31213168/53396868-89457980-39e0-11e9-8a52-6d950589484d.png)
These parameters do not tell which ones are required and which are optional.

**Comment by Chappell-C** [comment]
![image](https://user-images.githubusercontent.com/31213168/53399712-771b0980-39e7-11e9-871a-7104b628f1a0.png)
![image](https://user-images.githubusercontent.com/31213168/53399789-91ed7e00-39e7-11e9-89ae-09a2fbe5c89c.png)
I have some doubts about which set of parameter formats should I use when I use the ledger for signing.

**Comment by Chappell-C** [comment]
@btchip Can you provide some suggestions? Thank you very much

**Comment by Chappell-C** [comment]
@gre Can you give some advice?
