### ISSUE TITLE
[nano s][webusb] "NotFoundError The interface number provided is not supported by the device in its current configuration."

### ISSUE THREAD

**Issue by edouardswiac** [LedgerHQ/ledgerjs#302]
Hello everyone!

I am having issues contacting my nano s via webusb transport. Chrome sees the device because I am getting the pairing pop up, but my JS code fails to find it upon clicking on `Connect`

<img width="441" alt="screen shot 2019-02-26 at 11 30 53 am" src="https://user-images.githubusercontent.com/233253/53406325-06a9c380-39ba-11e9-9fa4-9f92fdf21159.png">

```js
      TransportWebUSB.create().then(transport => {
        const btc = new Btc(transport);
        btc.getWalletPublicKey("44'/0'/0'/0").then(o => console.log(o.bitcoinAddress));
      }).catch(err => {
        console.error([err.code, err.name, err.message]);
      });
```

```shell
[8, "NotFoundError", "The interface number provided is not supported by the device in its current configuration."]
```

**Comment by gre** [comment]
Thanks for creating this issue.

What is the version of your ETH app on the device? Firmware version of the device?

thanks

**Comment by edouardswiac** [comment]
Do I need the ETH app if I care only about BTC right now?

My device ran out of space so I uninstalled a bunch of apps and right now i only have the following:
- btc 1.2.8
- btc test 1.2.8
- fido u2f 1.2.4

Device: 
- MCU 1.5 
- Secure elements 1.4.2

I am going to update to the latest firmware and see if it helps.

**Comment by gre** [comment]
(oops sorry! I meant the btc version)

I think the webusb is only supported on the latest firmware version yeah.

**Comment by edouardswiac** [comment]
Cool thanks!

**Comment by chasedetwiler90** [comment]
Having the same issue but I know the firmware is up to date.  Any other ideas?
