### ISSUE TITLE
Failed to sign with Ledger device: U2F TIMEOUT

### ISSUE THREAD

**Issue by tphanson** [LedgerHQ/ledgerjs#305]
I read all the issue related but nothing seems like to my issue, so I created a new one.

I try to send a tx on Ethereum by Metamask. Every time, the confirmation is popped up, If I say yes immediately the tx will be successfull. But in case, I wait for a while (when the address of confirmation is shown) and then say yes, Metamask will show the error `Failed to sign with Ledger device: U2F TIMEOUT`.

Also, I tried and my own code and Myetherwallet, both were failed.

I was stuck in that issue for a day, and I am very thankful for you to get me around.

**Comment by Chappell-C** [comment]
When signing, there is a default timeout that failed to operate in time. I don’t know how long it takes.
And this time is different from the setExchangeTimeout method exposed by ledger.
setExchangeTimeout refers to the waiting timeout period of the connection hardware.
The default timeout means that this step of your operation, you failed to operate within a certain period of time.
Vaguely remember that this time is 7 seconds, the record is not clear, and this time can not be modified

**Comment by gre** [comment]
this is the reason https://github.com/LedgerHQ/ledgerjs/issues/306

**Comment by nyetwurk** [comment]
Except it isn't just chrome, and the ledger itself crashes every time the U2F signing process times out. Firefox, Brave, Chrome all show the same behavior.

**Comment by nyetwurk** [comment]
Also there is no sign that #306 is being addressed.

**Comment by gcsfred2** [comment]
The problem just happened to me now. Metamask waits for Ledger hardware wallet and the Ethereum app in Ledger doesn't do anything.

**Comment by artall64** [comment]
Same issue chrome 83.0.4103.106; `Os X`

**Comment by kaiba42** [comment]
any workarounds?
