### ISSUE TITLE
Chromium 72+ has broken Ledger U2F support

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledgerjs#306]
Any users that comes on a web app using `@ledgerhq/hw-transport-u2f` on *Chromium 72+* will fall into a bug that breaks Ledger device communication. (`U2F TIMEOUT` error).

### What happened?

*Chrome 72+* has started being rolled out around *February 21th, 2019*. This new version has changes in the U2F protocol implementation that is breaking Ledger's.

### What solutions

**In the short term**, Users can be advised to switch to *Opera* or *Brave* but it's probable that these browsers will upgrade Chromium as well.

**In the mid term**, we are working on a fix for U2F. It will only be a fix on the Ledger device side, meaning users will have to upgrade (the apps). If you are a developer of one of these applications, you can take a look at [this](https://github.com/LedgerHQ/nanos-secure-sdk/tree/1552-u2f-fix) for reference, for further questions please get in touch with [@btchip](https://twitter.com/BTChip/status/1100140458716606466) or discuss on our Slack Devs.

**In the long term**, switching to WebUSB is probably going to be the good plan. At the moment, this API is still a draft spec but we anticipate it will be more widely supported in the future. It is much more relevant for Ledger devices (more performant, more features like being able to detect disconnection,..)

Regarding `@ledgerhq/hw-transport-webusb` current implementation, it works on latest firmware / apps but there are some slight different in the way it works (coming from u2f) which have some UI/UX implication. We'll try to document it better in the next weeks.

**Comment by dschuermann** [comment]
Hi @gre,
do you know if the blocking of CCID and HID classes in Chrome (https://www.yubico.com/support/security-advisories/ysa-2018-02/) affects your plans to use WebUSB?

**Comment by gre** [comment]
it shouldn't be a problem.

**Comment by Luganova** [comment]
Hi!I know how to get around this error when signing transactions!

**Comment by Luganova** [comment]
everything works fine for binance DEX!

**Comment by BrendanEich** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=935131

**Comment by Luganova** [comment]
We are talking about windows or Linux?

**Comment by gre** [comment]
@Luganova from what we have seen it affects all platform.

**Comment by Luganova** [comment]
I agree! It is necessary to confirm the transaction in a split second! I did not have time-time out!

**Comment by gre** [comment]
It appears that a Chrome update may have solved the problem. Waiting for more confirmations.

**Comment by harshjv** [comment]
Working on latest chromium revision 637660. https://download-chromium.appspot.com/

**Comment by monokh** [comment]
On chrome 72, this also causes the error `Invalid data received (0x6a80)` when using `btc.signMessageNew` with certain sizes of message.

**Comment by brunobar79** [comment]
Still seeing this in the latest version of chrome - 73.0.3683.86 (Official Build) (64-bit)
Also tried it with the latest firmware + ledger lib and the timeout issue after ~3 seconds is still happening.

**Comment by giankotarola** [comment]
> On chrome 72, this also causes the error `Invalid data received (0x6a80)` when using `btc.signMessageNew` with certain sizes of message.

I get the same error with `eth.signTransaction` with chrome - 73.0.3683.86

**Comment by kjarada** [comment]
I'm having the same issue, despite the fact that ledger support advised using brave and opera browser but it's still not working in all these platforms with same error U2F Timeout.

**Comment by JeanoLee** [comment]
1.1.8

**Comment by ianaz** [comment]
> that ledger support advised using brave and opera browser but it's still not working in all these platforms with same error U2F Timeout.

Same here. It used to work with Brave a couple of weeks back but not it's broken there too

**Comment by dzsobacsi** [comment]
Here too. For me it used to work with Opera some weeks ago but now that does not work either.

**Comment by georgeliuyu** [comment]
It still timeout when I use the brave

**Comment by iicc1** [comment]
Not working for me too, I have tried Opera, Brave, last Chromium...
How can I send tokens?

**Comment by poserr** [comment]
@iicc1 for us the workaround was to quickly (during 1 second) confirm _twice_

**Comment by iicc1** [comment]
Thanks for you reply @poserr, I didn't see it. I was finally able to do with an old Brave releases that I downloaded here: https://github.com/brave/browser-laptop/releases

**Comment by dzsobacsi** [comment]
@iicc1 which one did you download from those?

**Comment by iicc1** [comment]
@dzsobacsi v0.25.300

**Comment by CiviStation** [comment]
Version 73.0.3683.103 (Official Build) (64-bit) U2F timeout still exists

**Comment by jakestpeter** [comment]
v.0.25.300 didn't work for me ...

**Comment by dzsobacsi** [comment]
Just realized that I made a stupid mistake. Once you update the Ethereum app on the Ledger, you have to go to settings and set "Contract data" to YES (again). With that setting, it worked for me with the latest release of Brave.

**Comment by jakestpeter** [comment]
@dzsobacsi - this seems to have fixed the problem ... THANK YOU!

**Comment by poserr** [comment]
For all users experiencing this issue - try to update Firmware on your device to the latest version (1.5.5) and update your Ethereum app as well (1.2.4)

**Comment by intsol** [comment]
This problem exists also with the NEO app.
I have found that closing the ledger app, requesting the signing, then opening the app and signing  works every time.
The first signing after app start appears to work.  While not ideal, it seems consistent.

**Comment by kjarada** [comment]
the problem is still there and driving me mad,i cant access my wallet.
i updated to latest firmware ,done everything ,downloaded older releases of chrome,brave and opera nothing is working.
please help

**Comment by SnearK6354** [comment]
Can you please confirm which Nano application you are using? And also the companion app you are using to access your funds ?

**Comment by ianaz** [comment]
I confirm what @dzsobacsi said. By updating the application you will have to re activate "Contract data"

**Comment by FabriceDautriat** [comment]
Hello, 

u2f time out error should be solved with the latest release of the applications and firmware (1.5.5).

If you still experience issues with applications, please confirm in your message :

- The FW version you have installed
- The name and version of the app you are using
- The **companion application** you are using 
_(for instance MEW for Ethereum, or ADALite for Cardano)_

We'll make sure to try to reproduce on your end.

Thanks a lot for your help.

**Comment by AdvocateOne** [comment]
I'm having this error as well.  Have tried all suggestions above and no luck.
Ledger Nano S
Firmware: 1.5.5
Ethereum App: 1.2.7
Tried using Chrome, Opera, and Brave
Windows 7 Professional (up-to-date security patches)
Tried with MEW and MyCrypto

Please help since I am effectively unable to access any of my tokens except for ETH (using Ledger Live)

**Comment by jakestpeter** [comment]
@AdvocateOne did you do what @dzsobacsi suggested above? (5 days ago) - That seemed to have done the trick for me ...

**Comment by AdvocateOne** [comment]
> @AdvocateOne did you do what @dzsobacsi suggested above? (5 days ago) - That seemed to have done the trick for me ...

Yes I did-- contract data set to yes.  Still get the timeout.

**Comment by harshjv** [comment]
See this https://github.com/LedgerHQ/ledgerjs/issues/332 for an alternative/workaround.

**Comment by FabriceDautriat** [comment]
@AdvocateOne, thank you for the information you provided.

We suspect this is related to USB driver on Windows 7. Can you try updating them ? 

https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues

Thanks a lot.

**Comment by AdvocateOne** [comment]
> @AdvocateOne, thank you for the information you provided.
> 
> We suspect this is related to USB driver on Windows 7. Can you try updating them ?
> 
> https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues
> 
> Thanks a lot.

That was the problem.  Thanks!

**Comment by jakestpeter** [comment]
I should have stated I was on a Mac - didn't even occur to me.

**Comment by intsol** [comment]
I have a reproducible case:
- Ledger Nano S
- Google Chrome Mac Version 74.0.3729.131 (Official Build) (64-bit)
- Firmware 1.5.5
- NEO App 1.3.3
- Switcheo Exchange Neo Wallet - NEO Deposit & Withdraw (https://switcheo.exchange)

If the signing is approved within 1 second of appearing on the Ledger display, it works.
If signing is delayed over 5 seconds, the result is a U2F timeout by the dApp.

I am part of the support team at Switcheo, so if you require further info please advise.

intsol

**Comment by FabriceDautriat** [comment]
Hello @intsol ,

Indeed the version 1.3.3 of the NEO app may induce error when used with a web browser. 
This is the standard u2f issue and will be solved with version 1.3.5 (compiled with new SDK and to be released soon).

However, we don't officially support https://switcheo.exchange. 

The main reason is that DEX operations are not correctly displayed within the NEO application. Users are required to sign without verifying any transaction details. 

I advise you to contact the NEO app developer to implement the necessary features to get validated.

So far the only wallet Ledger tested is https://neonwallet.com/.

Regards,

Fabrice Dautriat

**Comment by kjarada** [comment]
@AdvocateOne  thank you very much, I only needed to update the USB drivers on windows 7 and now is working perfectly on chrome.

**Comment by fuorissimo** [comment]
With Opera, the same problem. Nano X don't work with MEW.

Considering that you don't add erc20 native, i ask refund and i back you Nano X. Useless wallet

**Comment by amukhanchikov** [comment]
Same problem

- Ledger Nano X (Nano S as well)
- Google Chrome Windows Version 74.0.3729.169 (Official Build) (64-bit)
- Firmware 1.5.5
- Ethereum 1.2.7 + http://mycrypto.com
- Wanchain 1.2.7 + https://mywanwallet.io
- ICON 1.0.5 + ICONex

Everywhere above U2F error. Nothing helps.

Windows 10 64-bit with all drivers up-to-date.

The same error on Brave browser.

**Comment by gre** [comment]
@fuorissimo if you can afford to wait ~1 month , we will have LedgerLive supporting erc20 soon

**Comment by fuorissimo** [comment]
Ok, this is a good news. Thanks for your support

**Comment by amukhanchikov** [comment]
https://github.com/LedgerHQ/ledgerjs/issues/306#issuecomment-498055291

After updating to Chrome 75 - nothing changed. Still doesn't work. Any help or comment?

**Comment by marcinsx** [comment]
Ledger Nano S
Operating system: MS Windows 10.
Firmware: 1.4.2-das MCU 1.6 (it is Ledger Nano S modified for DasCoin)

Hi, what are my options to transfer ETH which are secured with Ledger Nano S?

I already tried MyEtherWallet at Chrome, Opera, Brave browsers. It worked in Februwary 2019 without any problems. Now the Ledger can't accept the transaction - I click accept at Ledger but no information goes to the Browser.

I also tried to connect it to Ledger Live app - but I even can't add ETH there - when I'm trying to do it, it discoveres Ledger but it goes back when I enter ETH app on Ledger.

What options do I have to just transfer my ETH? Are there any or I'm now blocked??? Maybe there are any other applications than web browsers and Ledger Live, which allow to access ETH wallet secured with Ledger?

**Comment by marcinsx** [comment]
OK I will answer myself. The only option I found is to install an OLD version of webbrowser - Opera or Chrome.

OId versions of Opera You can find here:
http://get.opera.com/ftp/pub/opera/desktop/ 
(I chose the 58.0.3135.53 version, You can find it here: http://get.opera.com/ftp/pub/opera/desktop/58.0.3135.53/win/ IMPORTANT: chose Setup version not Autoupdate, because You want to install an OLD version without updating to the newest one)

Old versions of Chrome You can find here (I didn't check downloading from here because I used Opera):
https://www.slimjet.com/chrome/google-chrome-old-version.php

After installing an OLD version of web browser, just simply go to mywetherwallet.com and viola! It works!

Good Luck!

**Comment by fuorissimo** [comment]
> 
> 
> @fuorissimo if you can afford to wait ~1 month , we will have LedgerLive supporting erc20 soon

You confirm is on the road, ERC20 support? when do you think is done?

**Comment by gre** [comment]
you can follow development https://github.com/LedgerHQ/ledger-live-desktop/pull/2057 (this is one milestone, there will be a few more work after this first PR but it's a good kickoff)

**Comment by dogperrokukur** [comment]
Having the same problems (ALERT: TransportError: Failed to sign with Ledger device: U2F TIMEOUT)
•	Ledger Nano S
•	Google Chrome version. 75.0.3770.90
•	Windows Version:  Win 10 (Official Build) (64-bit) OS Build 18362.175
•	Ledger Firmware 1.5.5
•	Ethereum App 1.2.7 
•	Metamask and MEW

Downloaded and installed earlier versions of Chrome, Brave, Opera and Firefox.  Nothing helps.  I am unable to move tokens from my ledger or engage in smart contract transactions on certain DEX, https://staking.linkpool.io/dex
This is a very serious issue.  Have not had access to tokens for several months.  Hoping for a speedy resolution.

**Comment by marcinsx** [comment]
Hi, did You try this concrete version of Opera 58.0.3135.53? It worked for me + I was using myetherwallet.com. Also, please remember uninstall first the "new" Opera which YOu may have installed in Your system. Also please try to restarting Your computer (but I think it worked by me without restarting). Good luck.

> OId versions of Opera You can find here:
> http://get.opera.com/ftp/pub/opera/desktop/
> (I chose the 58.0.3135.53 version, You can find it here: http://get.opera.com/ftp/pub/opera/desktop/58.0.3135.53/win/ IMPORTANT: chose Setup version not Autoupdate, because You want to install an OLD version without updating to the newest one)

**Comment by claytucker** [comment]
I have this error.
Ledger Nano S
Firmware: 1.5.5
dYdX Exchange accessed via MetaMask connected to Ledger Nano S
Tried using Chrome, Opera, and Brave
Tried using Windows 10 Home and Windows 7 Enterprise (up-to-date security patches). All six of these options create the same error. All my funds are essentially trapped on the dYdX Exchange/in the smart contract.

**Comment by dogperrokukur** [comment]
Thanks for all the suggestions.   I seem to have solved the problem independently, well at least temporarily.   But I’m still of the opinion this is a big issue for the community.  Like the above poster, I also lost access to my tokens.  More importantly I was unable to conclude several time sensitive trades on a DEX because of this “known issue”. I’m just amazed that this isn’t a bigger deal across the web.  I’m also amazed that this has not been solved yet.  Its been months now.   I’m sorry but the first post on this thread was in Feb.  Anyway enough, I’m sorry about the rant.  Here is what I did.   

First I uninstalled the latest version ofChrome and reverted back to an older version.  I installed a version that was released just before Feb 2019, when the known issue occurred.  I used Version 71.0.3578.80 (Official Build) (64-bit)
You’ll have to stop chrome from auto updating, (which it likes to do all the time).  Just do a quick search on the web to see how to do that.
In my particular case I was using metamask to complete my transactions.  
Initially I installed the latest version of Metamask, but that also seems to cause similar issues.  So I decided to use MetaMask 5.2.1.  This version was released around the same time as the Chrome version I have reverted to using.
You can also easily find this on the web.  When installing the metamask extension, use developer mode within the extension settings.
Then click on "load unpacked" and install the custom extension.  Not sure how to stop auto updates on metamask however.  You might have to reinstall over time.
Again I am not sure how long this will work for, and if it will work for everyone.  But it does prove that reverting to older web browsers does seem to be the way to go for now.

**Comment by shawnholt** [comment]
Tried everything.  old version of opera will only allow install of ver Version 3.14.1 of metamask which does not support Ledger!  There is NO WAY to access ERC 20 Tokens on Ledger.  This is crazy!

**Comment by shawnholt** [comment]
Error message: ![image](https://user-images.githubusercontent.com/2068714/59881648-1c366500-937e-11e9-8784-964c98921dab.png)

**Comment by Creamers158** [comment]
I used Chrome Beta and that one works for me ;)

**Comment by amukhanchikov** [comment]
Any updates or comments?
One month has passed since my first comment - still nothing works! Neither in Opera, nor in Chrome, neither Nano X, nor Nano S

**Comment by dmdque** [comment]
Worked with:

Metamask: 6.7.2
Chrome: 75.0.3770.100
Ledger Nano S: Secure Element: 1.55, MCU: 1.7

**Comment by TeslaNguyen** [comment]
Still getting "Failed to sign with Ledger device: U2F TIMEOUT" on Manjaro/Brave. What can I do? It's been weeks. :/

**Comment by nyetwurk** [comment]
Also hangs the Ledger dead.

**Comment by TeslaNguyen** [comment]
> Still getting "Failed to sign with Ledger device: U2F TIMEOUT" on Manjaro/Brave. What can I do? It's been weeks. :/

Alright, I could actually get around the aforementioned issue by following this link (granted, I probably should've look there earlier): https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues

I was missing this part: 

"wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash"

However, now I keep getting "Failed: need signature."

It's really not funny anymore.

**Comment by nyetwurk** [comment]
It is hilarious that they recommend searching for a driver for windows 10 that doesn't exist.

**Comment by nyetwurk** [comment]
> 
> 
> @AdvocateOne, thank you for the information you provided.
> 
> We suspect this is related to USB driver on Windows 7. Can you try updating them ?
> 
> https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues
> 
> Thanks a lot.

This simply doesn't work. There are no windows drivers that I can find. Please provide a direct download link for your drivers.

**Comment by nyetwurk** [comment]
> For all users experiencing this issue - try to update Firmware on your device to the latest version (1.5.5) and update your Ethereum app as well (1.2.4)


This does not work. On every browser (Chrome, FF, Brave, Opera) MM times out too soon. The topic of this bug should be changed to reflect this is a general problem with Ledger support and MetaMask. It should also include the fact that MM U2F hangs the ledger stone dead when attempting to sign an ERC20 transaction.

**Comment by nyetwurk** [comment]
Will https://github.com/LedgerHQ/nanos-secure-sdk/pull/21 fix this bug?

**Comment by nyetwurk** [comment]
https://github.com/MetaMask/metamask-extension/issues/6345

**Comment by seanatwork** [comment]
I sent some erc-20 tokens to my ledger prior to discovering this issue (trying to be safer!). Obviously I can't move them now in metamask . Am I SOL until this is resolved or a new ledgerlive is released?

I tried @dogperrokukur 's post of rolling back chrome/mm extension from Jun19 and the page just freezes on the "connect a hardware wallet" screen of metamask. Any assistance is greatly appreciated.

**Comment by btchip** [comment]
If you're running Windows 1903 please see https://www.reddit.com/r/ledgerwallet/comments/cxf3h9/new_beta_windows_pop_up_issue/ and report in the reddit thread if this fixed your issue

**Comment by nyetwurk** [comment]
Why is this discussion on reddit and not here?

**Comment by btchip** [comment]
For better visibility and follow up

**Comment by gre** [comment]
The situation should be back to normal (using latest firmware)

**Comment by jafri** [comment]
@gre what do we need to update for EOS?

**Comment by mitakash** [comment]
Still seeing this issue with Ledger Nano S firmware 1.6.0. Basically won't connect to Metamask. I can connect to Ledger Live 2.0.  
TransportError: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE  
Can someone please help? I am on  Ubuntu 18.04 LTS

**Comment by youfoundron** [comment]
+1 Seeing this error as well

**Comment by liamzebedee** [comment]
Me too. 🙌 WebUSB is broken with the ledger web3-subprovider.

**Comment by gre** [comment]
Please share a (minimal) example that reproduce the problem in a new Github issue because it's not easy to understand what exactly you are raising. this task is about U2F support issue we had a year ago and have nothing to do with WebUSB or web3-subprovider.
