### ISSUE TITLE
Include TypeScript definitions in NPM packages.

### ISSUE THREAD

**Issue by MicahZoltu** [LedgerHQ/ledgerjs#335]
It would be nice if TypeScript types were included with the NPM packages.  It appears that you are using Flow, so you have type information available, it just isn't exposed in a way that TypeScript can consume.  An example for how to do this would be to include a file named `Transport.d.ts` in `@ledgerhq/hw-transport/lib/` with contents like:
```typescript
/// <reference types="node" />

declare class Transport<TDescriptor extends Descriptor = string> {
    constructor();
    static isSupported(): Promise<boolean>;
    static list(): Promise<ReadonlyArray<Descriptor>>;
    static listen(
        observer: Observer<DescriptorEvent<Descriptor>>
    ): Subscription;
    static open(
        descriptor: Descriptor,
        timeout?: number
    ): Promise<Transport<typeof descriptor>>;
    static create(
        openTimeout?: number,
        listenTimeout?: number
    ): Promise<Transport<Descriptor>>;
    exchange(apdu: Buffer): Promise<Buffer>;
    setScrambleKey(key: string): void;
    close(): Promise<void>;
    on(eventName: string, cb: any): void;
    off(eventName: string, cb: any): void;
    setDebugMode(debug: boolean | ((log: string) => void)): void;
    setExchangeTimeout(exchangeTimeout: number): void;
    send(cla: number, ins: number, p1: number, p2: number, data: Buffer, statusList: ReadonlyArray<number>): Promise<Buffer>;
}

export type Device = any;
export type Descriptor = string; // ?
export interface DescriptorEvent<Descriptor> {
    type: "add" | "remove";
    descriptor: Descriptor;
    device?: Device;
}
export interface Observer<Ev> {
    readonly next: (event: Ev) => any;
    readonly error: (e: any) => any;
    readonly complete: () => any;
}
export interface Subscription {
    readonly unsubscribe: () => void;
}
export function getAltStatusMessage(code: number): string;
export const StatusCodes: {[k in string]: number};

export default Transport;
```

This will make it so users who are using TypeScript and/or a TypeScript aware editor will get type hints and compile-time checks.

If a Pull Request for something like this would be accepted, I can help you get started using types from DefinitelyTyped (written by other users) and some I have locally (written by me).  The caveat here is that I'm not sure what the preferred/best way to get non-generated files into the output directory.  It is possible there is something that auto-generates definition files from flow source, but as I'm not familiar with flow I don't know how to do that.

**Comment by gre** [comment]
Or maybe rewrite ledgerjs in TypeScript ^^

**Comment by webmaster128** [comment]
Some initial transport types are on Definitely Typed now:
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ledgerhq__hw-transport
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ledgerhq__hw-transport-node-hid
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ledgerhq__hw-transport-u2f

I added some fixes recently and am planning to add webusb we well. Check it out and send a fix if something is wrong/missing. It is a nice place over there.

**Comment by QuestofIranon** [comment]
I added webusb definitions  based on @webmaster128's entries, it's still waiting for approval.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38795

**Comment by gre** [comment]
For now, I would recommend to put types on DefinitelyTyped, there are no ETA on when we will migrate to TS but we still have it in mind. i'll close the issue for now. Thanks
