### ISSUE TITLE
Ledger signature btc transaction failed

### ISSUE THREAD

**Issue by Ark-Chen** [LedgerHQ/ledgerjs#339]
Hardware return：Ledger device: Internal error, please report (0x6faa)

The strangest thing is that it is good or bad，and I use exactly the same data.

And I have multiple ledgers, in different firmware versions, first of all this problem.This problem has appeared since yesterday. It is ok, sometimes it will return this error.My hardware has two latest firmware and the latest app, and this problem still exists.

I should be able to confirm that there is no problem with the data I passed in.

Is this problem related to the change of chrome u2f?

**Comment by Chappell-C** [comment]
Currently only btc signatures have this problem.

**Comment by Chappell-C** [comment]
After my test, if the instruction needs to be confirmed multiple times after reaching the hardware, the interval of each confirmation will only take 1 second, and the return signature of the hardware will not be obtained. Finally, the timeout will be returned, and the instruction hardware sent again will be sent again, may return "0x6faa".
I think this might be a bug in the app（version 1.3.8）.
