### ISSUE TITLE
Can't send ERC20 token

### ISSUE THREAD

**Issue by brunobar79** [LedgerHQ/ledgerjs#341]
Just found out that this is not working while trying to send an ERC20 token.
Tried via MetaMask and MyCrypto and both are showing the same error:

TransportStatusError: Ledger device: Invalid data received (0x6a80)

MetaMask:

![Screen Shot 2019-04-15 at 12 48 26 PM](https://user-images.githubusercontent.com/1247834/56150678-6285d700-5f7d-11e9-8aed-a5b828ab2342.png)

MyCrypto:

![Screen Shot 2019-04-15 at 12 50 07 PM](https://user-images.githubusercontent.com/1247834/56150668-57cb4200-5f7d-11e9-8b51-a171813f5b5e.png)

Using Ledger NANO 
- firmware v1.5.5
- ETH app 1.2.4
- MetaMask is using the following deps:
- hw-app-eth: "^4.48.0",
- ledgerhq/hw-transport-u2f: ^4.48.0",
- Network: Rinkeby
- TOKEN: VPP - https://rinkeby.etherscan.io/token/0x8dc5de7dc295cbdcc9fb17afa3473da26f005a04

**Comment by gre** [comment]
@brunobar79 It could either be related to an unknown token OR maybe contract data is not activated in settings?

In any case, i'm interested to know because there might be an error message to improve here!

**Comment by brunobar79** [comment]
@gre thanks for the info. I can send any other know token (BAT for example) so I don’t think it’s about contract data not being enabled in the device.

Def. a unknown token. For the record, This is our implementation:

https://github.com/MetaMask/eth-ledger-bridge-keyring/blob/gh-pages/ledger-bridge.js#L82

(I can confirm that `byContractAddress` is returning undefined)

**Comment by gre** [comment]
@brunobar79 and are you sure you have enabled in the device app the "contract data".

what @btchip told me is that `if you sign an unknown erc20 it's seen as a vanilla contract, so you should have "contract data" enabled`

**Comment by brunobar79** [comment]
You're right. I had it disabled. Just enabled it and it worked like a charm.  A more descriptive msg would be nice but feel free to close this issue if you want. 

Thanks!

**Comment by gre** [comment]
https://github.com/LedgerHQ/ledgerjs/commit/38b7aabf67e050b212037f249223a59460149c88
