### ISSUE TITLE
Safari Preview 71 landed support for Web Authentication API

### ISSUE THREAD

**Issue by fnando** [LedgerHQ/ledgerjs#348]
Now that Safari has support for [Web Authentication API](https://webkit.org/blog/8517/release-notes-for-safari-technology-preview-71/), will Ledger Nano S work on Safari?

Is this being tracked already?

**Comment by gre** [comment]
WebAuthn as a Ledger transport have disastrous user experience at the moment so I wouldn't recommend it much.

![wag](https://user-images.githubusercontent.com/211411/57580560-81f41f00-74ab-11e9-98f0-f24f6928bc05.gif)

this modal shows up for 50ms & for **each** individual device communication (APDU), sometimes longer if you need to accept on the device or if it's slow to respond. Maybe there is a way to tell Web Authentication API to run "silently" but I didn't found. maybe something to dig in future https://github.com/w3c/webauthn/issues/199 https://github.com/w3c/webauthn/issues/22 <- It seems they say the V1 won't have such feature, V2 maybe
