### ISSUE TITLE
Request: Keep a CHANGELOG

### ISSUE THREAD

**Issue by MisterTicot** [LedgerHQ/ledgerjs#354]
It would be great to have a CHANGELOG.md at the root of the repository. Updates are frequent & it would be nice to be able to quickly know about introduced changes.

I'm maintaining a [library helper](https://github.com/cosmic-plus/node-ledger-wallet) for Stellar & I'd like to be able to easily spot when updating Ledger libs is relevant or not. Obviously I know about commit history, but a few sentence that clarify the content of releases would really help.

**Comment by MisterTicot** [comment]
(please)

**Comment by gre** [comment]
Duly noted

**Comment by gre** [comment]
we're going to track it in https://github.com/LedgerHQ/ledgerjs/releases

**Comment by MisterTicot** [comment]
@gre Thank you very much for that awesome reactivity!
