### ISSUE TITLE
Add function to get device firmware version and app version

### ISSUE THREAD

**Issue by Mrtenz** [LedgerHQ/ledgerjs#365]
Ledger Live has some functions to get the device info (device ID, firmware version and app with version):

* https://github.com/LedgerHQ/ledger-live-common/blob/master/src/hw/getVersion.js
* https://github.com/LedgerHQ/ledger-live-common/blob/master/src/hw/getAppAndVersion.js
* https://github.com/LedgerHQ/ledger-live-common/blob/master/src/hw/getDeviceInfo.js

It would be nice if these functions could be implemented in LedgerJS itself (e.g. in `hw-transport`), so other users can easily implement this as well, without having to copy all this code. Ledger Live could be updated to use these new functions instead.

**Comment by gre** [comment]
I'm afraid this is beyond scope of ledgerjs transport. Maybe we could offer them in another library but it's not part of hw-transport's job

**Comment by Mrtenz** [comment]
Right, that makes sense. It could be a new package like `hw-info` or something?

**Comment by gre** [comment]
or `hw-dashboard` because it's about APDUs that can only be run in the "dasboard" context of the device (and apps have hw-app-* bindings libs).

**Comment by sterlu** [comment]
Should it be possible to query this directly? I tried 
```js
transport.setScrambleKey('w0w')
const res = await transport.send(0xe0, 0x01, 0x00, 0x00);
``` 
but I get `Ledger device: INS_NOT_SUPPORTED (0x6d00)`. I tried using U2F and WebUSB transports.

**Comment by gre** [comment]
only if you are on the dashboard of the app, not from inside the ethereum app

**Comment by sterlu** [comment]
@gre I tried both the dashboard and the app. One just times out and the other one throws the message above

**Comment by flocks** [comment]
is `w0w` the scramble key of the dashboard?

**Comment by sterlu** [comment]
Yes

**Comment by gre** [comment]
I think for the dashboard, it's `"B0L0S"` (with zeros, not Os)

**Comment by flocks** [comment]
> Yes.
> Edit: "w0w" is the key I set using transport.setScrambleKey. Not sure what it is exactly. But it does work for other requests.

With u2f transport, you have to specify the app you want to talk to ( the dashboard being like an application ). You do that by specifying the `scramble key`. `B0L0S` is the scramble key of the dashboard.

**Comment by sterlu** [comment]
Confirming, it works from the dashboard with  `transport.setScrambleKey('B0L0S')`
Thanks for the help @gre and @flocks 🙏
