### ISSUE TITLE
transport.deviceModel.productName set to Ledger Nano S while using a Nano X

### ISSUE THREAD

**Issue by PaulBernier** [LedgerHQ/ledgerjs#374]
`transport.deviceModel.productName` is set to "Ledger Nano S" while using a Nano X connected in usb with the `@ledgerhq/hw-transport-node-hid-noevents` package.

```javascript
          const transport = await Transport.create();
          console.log(transport.deviceModel);
```
yields:
```javascript
{
  id: 'nanoS',
  productName: 'Ledger Nano S',
  productIdMM: 1,
  legacyUsbProductId: 1,
  usbOnly: true
}
```

**Comment by pbondoer** [comment]
Hey @PaulBernier, I've managed to reproduce the issue. I've pushed #380 which should fix it. In the meantime, you can rely on `transport.device.getDeviceInfo()` instead :mag:
