### ISSUE TITLE
hw-transport-node-hid-* slow/resource heavy

### ISSUE THREAD

**Issue by DalderupMaurice** [LedgerHQ/ledgerjs#389]
Reading [this section](https://www.npmjs.com/package/node-hid#cost-of-hiddevices-and-new-hidhid-for-detecting-device-plugunplug) of `node-hid` (a package used in the repo), it is not recommended to use `HID.devices` to [poll for devices](https://github.com/LedgerHQ/ledgerjs/blob/master/packages/hw-transport-node-hid/src/listenDevices.js#L43) as it can drastically slow down the reading/writing and slows down other USB devices as well. ([code reference in package](https://github.com/LedgerHQ/ledgerjs/blob/master/packages/hw-transport-node-hid-noevents/src/TransportNodeHid.js#L25))

Knowing this, it would be beneficial to implement the recommended way of polling devices to speed up the process and prevent other devices from being slowed down as well.

**Comment by gre** [comment]
fun fact: [we are the reason](https://github.com/node-hid/node-hid/pull/272) that **node-hid** added this recommendation disclaimer in the README =)

It's important to know that this is a problem only in a context of you calling either `create()` or `listen()`. If you stop listening (aka .unsubscribe) it will no longer do polling.

also we have introduced other implementation of hid package:

- `@ledgerhq/hw-transport-node-hid` – uses node-hid and usb => it's not actively doing polling but only when there are usb events.
- `@ledgerhq/hw-transport-node-hid-noevents` – uses only node-hid  => Does not provide even provide USB events. so it's just going to try to `open()` (after one devices() call, no polling)
- `@ledgerhq/hw-transport-node-hid-singleton` – uses node-hid and usb-detection => it's going even further: when you `open()`, it's going to give you back the previous transport instance if it was not yet disconnected. if you have a series of open() and close() it's not effectively going to close the usb but will do one opening and will keep the instance until it disconnects (usb-detection). *side note: It's a bit more experimental but we hope to ship this in a near future in Ledger Live => this implementation is available over **Experimental > Experimental USB** in LedgerLive 1.12.0*

**Comment by DalderupMaurice** [comment]
Alright, thanks for the quick & kind response! 

To my concerns, this can be closed, thanks for the info! :)
