### ISSUE TITLE
write a web example

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledgerjs#39]
https://github.com/LedgerHQ/ledger-node-js-api/tree/multi-pkgs/packages/example-browser

**Comment by roosmaa** [comment]
Maybe this will be useful for someone who is looking for some ledger.js sample code (at least until the official example is published). Here's a sample React app that I created (for the Nano [currency]):  [roosmaa/hw-app-nano-sample](https://github.com/roosmaa/hw-app-nano-sample). It uses ledger.js and U2F transport to communicate with the Nano [currency] Ledger app.

**Comment by gre** [comment]
nice! yeah I think a "list of apps" showcase list would be a good idea
