### ISSUE TITLE
Still getting "Failed: need signature." and it's UNACCEPTABLE

### ISSUE THREAD

**Issue by TeslaNguyen** [LedgerHQ/ledgerjs#391]
I apologize upfront should this came across as harsh and entitled or whatever you'd like to call it. I personally think it's warranted and called for.

It's been weeks that I could access my funds. Weeks! I don't care who's to blame; whether it's Windows, Linux, some other OS, whether it's some browser or it's Ledger themselves. I don't care. All I care about is that you get this fixed ASAP. There is not a single reason this shouldn't be top priority to be resolved INSTANTLY.

I've had funds on exchanges which I have literally ZERO CONTROL over. I can't even cancel open orders because the device won't let me, let alone get funds off of exchanges.

The support we're getting on the matter is - pardon my French - pathetic. 

I've tried both Windows and Linux (multiple builds each), multiple USB ports and numerous different browsers, and none of them worked. 

I/we paid good money for security and yet we're sitting here with our d**** in our hands hoping that one day we're able to access our funds again.

I'm not even one of the big players (not that it mattered) but we're talking about thousands of unaccessible dollars. It's UNACCEPTABLE. Fix it!

**Comment by btchip** [comment]
If you're in a hurry you can always recover with your mnemonic. You don't even specify which application is affected, so I'm afraid there's not much that can be done to help you.

**Comment by TeslaNguyen** [comment]
You know full well which application is affected. It's both ETH and Binance Chain.

"If you're in a hurry you can always recover with your mnemonic."

I can't believe you just said that, are you for real? If I wanted to expose my key on some website I wouldn't have paid 100 EUR for the Ledger device smh

Your response fits the entire support we're getting on the issue tho, I'm not even surprised.

**Comment by gre** [comment]
Please contact our tech support. Github is not the place. Thanks
