### ISSUE TITLE
Buffer not defined [Angular 8]

### ISSUE THREAD

**Issue by Jeroen96** [LedgerHQ/ledgerjs#392]
Hi,

I'm trying to get the ledger libs to work with Angular 7/8. I've tried with the ../hw-transport-u2f first but i get the regeneratorRuntime error (#332). Using the recommended hw-transport-webusb results in a Buffer not defined error. This error also shows up after 'fixing' the regenerator with babel-polyfill when using the u2f lib.

![image](https://user-images.githubusercontent.com/10827065/62945164-813a9400-bdde-11e9-9d3b-3bb45364fbfb.png)

This error is generated in a fresh Angular 8.2.0 project.

only code being called is (structure omitted for readability):

```Typescript
import TransportWebUSB from '@ledgerhq/hw-transport-webusb';
if (TransportWebUSB.isSupported()) {

    }
```

**Comment by meriadec** [comment]
looks like you need a Buffer polyfill (module bundlers like webpack does that automatically). check [this](https://stackoverflow.com/questions/50371593/angular-6-uncaught-referenceerror-buffer-is-not-defined) or [this](https://github.com/agoncal/swagger-ui-angular6/issues/2).

**Comment by aleffabricio** [comment]
Hello @Jeroen96 , I solved this problem by placing in the polyfills.ts file:

`(window as any).global = window;`
`window.Buffer = window.Buffer || require('buffer').Buffer;`

**Comment by magicsign** [comment]
That doesn't work : 

  ERROR in src/app/app.component.ts(13,16): error TS2339: Property 'Buffer' does not exist on type 'Window'.
    src/app/app.component.ts(13,32): error TS2339: Property 'Buffer' does not exist on type 'Window'.

**Comment by aleffabricio** [comment]
> Isso não funciona:
> 
> ERRO no src / app / app.component.ts (13,16): erro TS2339: A propriedade 'Buffer' não existe no tipo 'Window'.
> src / app / app.component.ts (13,32): erro TS2339: A propriedade 'Buffer' não existe no tipo 'Window'.

Hello @magicsign, in which version did you install the buffer library? mine is at 5.4.2 and I noticed that the library was recently updated to 5.5.0 and I haven't tested this version yet. Version 5.4.2 still works normally for me.
