### ISSUE TITLE
Publish ES6 Modules

### ISSUE THREAD

**Issue by MicahZoltu** [LedgerHQ/ledgerjs#397]
The libraries, including the web libraries, all appear to be compiled for CommonJS only.  Recommend including a `module` property in `package.json` for each of the packages that points at a build that targets ES6 modules.

**Comment by gre** [comment]
definitely need to explore that in the next major rework of our build system (for the context we are also considering a major lib rework with typescript)

**Comment by MicahZoltu** [comment]
I would love to see a move to TypeScript.  However, not being written in TS is a minor inconvenience that I can work around, while not having ES6 modules is notably more painful, so if I had my way I wouldn't delay ES6 support in lieu of TS support.

**Comment by Mrtenz** [comment]
I would like an ES6 version of Ledger.js packages too. I'm using `@ledgerhq/transport-web-ble` for example, and currently it requires all of `rxjs` to be bundled. That's about 350 KB, over a third of my whole application. A rewrite to TypeScript is an added bonus.

**Comment by gre** [comment]
@Mrtenz I'm not sure to understand why a ES6 module would help on the bundle size, the lib would still depends on rxjs.
I will take a look of it's possible to tweak the rxjs import to lower the bundle size but I'm not sure.

**Comment by Mrtenz** [comment]
@gre I'm assuming Ledger.js is not using all features of Rxjs? Rxjs has an ES6 version, and if Ledger.js is an ES6 module too, Webpack should be able to do tree shaking and remove any unused parts of Rxjs. At least, I think. I'm using Babel to generate an ES module [here](https://github.com/FindETH/wallets/blob/ab91ec31ca25bbce0331f843cd48ab358af42d3b/package.json#L25), and in [my Webpack bundle](https://github.com/FindETH/web/tree/7f496262f738616fb2c11e2b6929bee1ab10ec87) any unused stuff is removed (you can try for yourself with `yarn build:analyze`).

350 KB seems rather large for an Observer library in the first place though. 😅

**Comment by gre** [comment]
Thanks, that's useful i'll try on my end.

**Comment by gre** [comment]
@Mrtenz could you tell me if `5.1.1-alpha.2` have fixed the problem? Using `parcel` I don't see any change but I suspect parcel does not use `"module"` entry point but always the `"main"`
thanks

**Comment by Mrtenz** [comment]
@gre This reduced the size for Rxjs from about 320 KB to 156 KB! A 50% reduction just by using ES modules. I really appreciate you looking into this!

**Comment by gre** [comment]
Ok thanks. i'll finalize something and it should be pushed in our next ledgerjs versions

**Comment by gre** [comment]
I wonder how to solve this for a "multi-entry" library, i mean, if library have more than just one entry point. This is the case of `rxjs`, and for instance we do `import {map} from "rxjs/operators"`

**Comment by Mrtenz** [comment]
Webpack (and other module bundlers like Rollup) should be able to detect the usage and tree shake regardless. Rxjs is a [pure](https://github.com/ReactiveX/rxjs/blob/master/package.json#L9) library, so if certain aspects of the code are not used they can be removed. With CommonJS-style imports (`const rxjs = require('rxjs')`), this becomes a lot more difficult.

**Comment by gre** [comment]
makes sense. (woo I didn't know about this `sideEffects` feature)

**Comment by gre** [comment]
this is now fixed (version `5.2.0`)
