### ISSUE TITLE
Stellar "Manage Buy Offer" support in hw-app-str

### ISSUE THREAD

**Issue by shiny-mountain** [LedgerHQ/ledgerjs#403]
https://www.stellar.org/blog/protocol-11-improvements-stellar/#the-introduction-of-buy-offers
in Stellar protocol 11 - "manage offer" operation was named "manage sell offer" and added new operation "manage buy offer". 
After signing operation by Ledger Nano S  we receive the error "Hash signing not allowed. Have you enabled it in the app settings?", because when status of response is the 'SW_UNKNOWN_OP' we call the "signHash_private" method in Str.js.

**Comment by MisterTicot** [comment]
A pull request adding it is waiting in Stellar app repos since one month now. (https://github.com/LedgerHQ/ledger-app-stellar/pull/6)

Could be nice if someone from Ledger could ping the dev in charge.

**Comment by gre** [comment]
when this PR gets merged feel free to contribute back to ledgerjs. You can also contact us on our devs slack for discussing about Stellar app. thanks
