### ISSUE TITLE
Simple example for Ledger web-integration on raw javascript?

### ISSUE THREAD

**Issue by pavlovdog** [LedgerHQ/ledgerjs#406]
I'm trying to develop simple web-page with the following pipeline:

- Detecting Ledger is available
- Detecting a Bitcoin app is enabled
- Getting some Bitcoin address from the Ledger
- Some X satoshis from this address

I'm using the example from the documentation. For compiling I'm using the `watchify index.js -o bundle.js`.

Here's my `index.js`:

```javascript
require("regenerator-runtime");
const Transport = require("@ledgerhq/hw-transport-webusb");
const AppBtc = require("@ledgerhq/hw-app-btc");

const getBtcAddress = async () => {
  const transport = await Transport.create();
  const btc = new AppBtc(transport);
  const result = await btc.getWalletPublicKey("44'/0'/0'/0/0");
  return result.bitcoinAddress;
};

getBtcAddress().then(a => console.log(a));
```

And I'm facing the problems already:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

I have added `require("regenerator-runtime");` on the first line and now I have the following error:

```
Uncaught (in promise) TypeError: Transport.create is not a function
```

**Details**
- Ledger nano S
- `uname -a
Linux pavlovdog 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
- Chromium Version 77.0.3865.90 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

P.S. Actually, with some help I can finish my MVP and create a separate repo for beginners. I think it will be pretty useful for newcomers (as my now).

**Comment by gre** [comment]
you can look at https://github.com/LedgerHQ/ledgerjs-examples

in commonjs style you need to do this

```
const Transport = require("@ledgerhq/hw-transport-webusb").default;
const AppBtc = require("@ledgerhq/hw-app-btc").default;
```


for regenerator-runtime, I think in fact you need

```
require("babel-polyfill")
```


we wish to improve our build system in a near future to prevent that need
