### ISSUE TITLE
How to integrate Ledger JS in Laravel framework

### ISSUE THREAD

**Issue by osiz-blockchainapp** [LedgerHQ/ledgerjs#411]
Hi,

How to integrate Ledger JS in laravel framework. Because I have used the PHP laravel framework. That source how to connect ledger nano s device.
kindly help us.

**Comment by poserr** [comment]
These are completely different technologies - PHP runs on server side, while JS (and ledger.js) is running in browser (client side). You cannot integrate Ledger.js in Laravel framework

**Comment by hackmod** [comment]
I guess, the Laravel also use js anyway, so you can connect Ledger Nano S at js level (client-side)
like as follow
~~~js
function createLedger(transport){
	var ledger = new ledgerEth(transport);

	ledger.getAddress("m/44'/60'/0'/0/0",false,true)
	.then(function(addr){
		console.log(JSON.stringify(addr));
	})
	.catch(function(err){
		console.log(err);
	});
}
...		u2fTransport.create(10000, 10000) // or webUsbTransport.create()
		.then(createLedger)
		.catch(function(err){
			console.log(err);
		});

~~~

**Comment by gre** [comment]
ledgerjs libraries are agnostic of frameworks it's used with.
