### ISSUE TITLE
Automatically Approve Ethereum Txs

### ISSUE THREAD

**Issue by JoseMiguelHerrera** [LedgerHQ/ledgerjs#412]
Hi there,
I'm building an app that needs to send transactions to the ethereum blockchain every 30 seconds or so, and I need the key to stay secure - so I naturally bought a ledger nano x.

I started using @ledgerhq/web3-subprovider to sign transactions and it works...however I need to approve them manually on the device. I know it would reduce security, but my application needs to automatically approve the txs.

What can I do?

**Comment by gre** [comment]
I think this request is beyond ledgerjs libraries. Please contact our tech team on Slack Devs (if you don't have access feel free to ping me with your mail and i can give you)
