### ISSUE TITLE
Instalation problem with yarn

### ISSUE THREAD

**Issue by AbadianFatemeh** [LedgerHQ/ledgerjs#421]
I have got these warning while installing package with yarn.

[1/4] Resolving packages...
warning babel-cli > chokidar > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
warning documentation > chokidar > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
warning documentation > git-url-parse > parse-domain > jest > jest-cli > @jest/core > jest-haste-map > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
info There appears to be trouble with your network connection. Retrying...
warning documentation > git-url-parse > parse-domain > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > @ledgerhq/example-browser > babel-preset-react-app > babel-preset-env > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > @ledgerhq/hw-app-ada > joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > documentation-website > react-scripts > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > @ledgerhq/hw-app-ada > joi > topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > documentation-website > react-scripts > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > documentation-website > react-scripts > extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > @ledgerhq/hw-app-ada > joi > hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > @ledgerhq/hw-app-ada > joi > topo > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > documentation-website > react-scripts > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > documentation-website > react-scripts > sw-precache-webpack-plugin > sw-precache@5.2.1: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > documentation-website > react-scripts > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > documentation-website > react-scripts > sw-precache-webpack-plugin > sw-precache > sw-toolbox@3.6.0: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > @ledgerhq/web3-subprovider > web3-provider-engine > ethereumjs-vm > merkle-patricia-tree > level-ws > xtend > object-keys@0.4.0: 
warning workspace-aggregator-86739658-4a84-4432-b541-05e1dd236c56 > documentation-website > react-scripts > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

whats is the problem with my installation?  
my os is ubuntu 19
node -v
v8.9.4

yarn -v
1.19.1
npm-v
5.6.0

**Comment by gre** [comment]
Please try again on our latest stack and using Node 12. It should work, we are having the libraries compiling on the CI
