### ISSUE TITLE
Transport for speculos emulator hw-transport-speculos

### ISSUE THREAD

**Issue by AndreyBronin** [LedgerHQ/ledgerjs#429]
Hello

I want to make some integration tests for my WebWallet app and Ledger Nano S and run it on CI.

Headless [speculos emulator](https://medium.com/ledger-on-security-and-blockchain/speculos-1709aa5fbec6) is good tool for this, but I need special transport for sending APDU codes from web app.

**Comment by gre** [comment]
@greenknot can you share what was your setup so far? I believe it was working with some python script and the proxy transport?
We could definitely write a more dedicated tool.

**Comment by greenknot** [comment]
Here is the command-line that I used in conjunction with speculos:

```
./tools/ledger-live-http-proxy.py &
DEBUG_COMM_HTTP_PROXY=http://127.0.0.1:9998 ledger-live getAddress -c btc --path "m/49'/0'/0'/0/0" --derivationMode segwit
```

- https://github.com/LedgerHQ/speculos/blob/master/tools/ledger-live-http-proxy.py
- https://github.com/LedgerHQ/speculos/blob/master/doc/usage.md#ledger-live-common

**Comment by AndreyBronin** [comment]
I also find websockify proxy in [run.sh](https://github.com/LedgerHQ/speculos/blob/master/run.sh) which runs in [Dockerfile](https://github.com/LedgerHQ/speculos/blob/master/Dockerfile). I think it's good solution for me to use  speculos with websockify proxy and hw-transport-http. 

Unfortunately Dockerfile is broken, I'll try to fix it and test

**Comment by gre** [comment]
@AndreyBronin i've just wrote a tcp transport that works great as shown on the PR description. I'll iterate with the team behind speculos to see if we can simplify to the bare minimum what the docker is about because essentially we just need to be able run ./speculos.py directly, provide some tcp ports and connect to it, without need to have extra proxy complexity
