### ISSUE TITLE
How to create broadcastable ETH transaction ?

### ISSUE THREAD

**Issue by eswak** [LedgerHQ/ledgerjs#43]
Hi guys,
I'd like to integrate the ledger on my website in order to sign transactions; but I'm stuck on a little detail.

For this purpose, I'm using this ledger library to sign the transaction; and I also use [ethereumjs/ethereumjs-tx](https://github.com/ethereumjs/ethereumjs-tx) to create the raw transactions in hex.
However, the transactions I'm creating do not seem to be properly formatted, I get the following error when broadcasting using [etherscan](https://etherscan.io/pushTx?hex=0xf86a018502cb417800825208946ef71ca9cd708883e129559f5edbfb9d9d5c6148865af3107a4000805ba0f4611d559d1db7c034236ef3989b43304b2e8ffd5855cead12da8f8f10c1db4fa068acbc380b551cd883db4b995f50df01533efef09f2529d85d205a6dd83e8f43):

`Error! Unable to broadcast Tx : {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"invalid sender"}}`

Here is how I use the libs :
```js
var raw = {
  "nonce": "0x1",
  "gasPrice": "0x2cb417800",
  "gasLimit": "0x5208",
  "to": "0x6ef71ca9cd708883e129559f5edbfb9d9d5c6148",
  "value": "0x5af3107a4000",
  "chainId": 1
};

var txToSign = new ethereumjs.Tx(raw).serialize().toString('hex');

new ledger.eth(comm).signTransaction_async('44\'/60\'/0\'/0', txToSign).then(function(result) {
  raw.r = '0x' + result.r; // "0xf4611d559d1db7c034236ef3989b43304b2e8ffd5855cead12da8f8f10c1db4f"
  raw.s = '0x' + result.s; // "0x68acbc380b551cd883db4b995f50df01533efef09f2529d85d205a6dd83e8f43"
  raw.v = '0x' + result.v; // "0x5b"

  var txSigned = new ethereumjs.Tx(raw);

  console.log('tx raw', raw);
  console.log('tx signed', txSigned.serialize().toString('hex')); // 0xf86a018502cb417800825208946ef71ca9cd708883e129559f5edbfb9d9d5c6148865af3107a4000805ba0f4611d559d1db7c034236ef3989b43304b2e8ffd5855cead12da8f8f10c1db4fa068acbc380b551cd883db4b995f50df01533efef09f2529d85d205a6dd83e8f43
}).catch(function() {});
```

The message prompts correctly on the ledger, and I can sign the transaction using the embedded ethereum app.

I'm not sure this issue is related to the `ledger-node-js-api` (could be how I use `ethereumjs-tx`) but in any case I think my use-case is pretty much representative of what we'd like to do with it in a browser so maybe it will help you guys provide a more complete example.

I'd be interested in a bitcoin example too.

**Comment by florianlenz** [comment]
I also get an `invalid sender` error. Do you guy's mind to look into it? 

You can try my repository in order to reproduce it. 

1. Clone the repo: https://github.com/florianlenz/HDWalletLedgerProvider
2. Run `npm install`
3. Run `node debugging_test.js`, sign the transaction and you will see that with the `invalid sender` error

**Comment by eswak** [comment]
Can somebody look into this issue ? Maybe @gre ? I see you committed a lot to this project recently.

We'd really like to have a ledger integration on our website. I tried to look into MEW and Etherdelta's code without much help :-(

**Comment by gre** [comment]
Hi @eswak , maybe have a look at [this code](https://github.com/LedgerHQ/ledgerjs/blob/master/packages/web3-subprovider/src/index.js#L134-L175): it implements a web3 subprovider for `web3-provider-engine` – now obviously some work is done by the web3 library, for instance, txData already have some fields filled by web3.
according to your error **"invalid sender"** makes me think maybe you miss to provide a `from` field ?

`from` needs to be the same address corresponding to the one pointed by the derivation path.

Additionally, I think you need to inspire from the code above to fill in the "network id". At some point we will move this logic back into an higher level function but for now it is on user land.

**Comment by eswak** [comment]
Hi guys,

I managed to work things out !!

The raw transaction object needs to be initialized with the `chainId` in its `v` value before signature. As follows : 
```js
var raw = {
  "nonce": "0x1",
  "gasPrice": "0x2cb417800",
  "gasLimit": "0x5208",
  "to": "0x6ef71ca9cd708883e129559f5edbfb9d9d5c6148",
  "value": "0x5af3107a4000",
  "chainId": 1,

  // add these :
  "v": "0x01",
  "r": "0x00",
  "s": "0x00"
};

var txToSign = new ethereumjs.Tx(raw).serialize().toString('hex');

new ledger.eth(comm).signTransaction_async('44\'/60\'/0\'/0', txToSign).then(....
```

Otherwise, the signature was invalid.

This line from MEW code hinted me to the right direction : https://github.com/MyEtherWallet/MyEtherWallet/blob/00a84ec0c5f49d143e036c902c14496fa659593d/common/libs/wallet/deterministic/ledger.ts#L22

Then to create the transaction to broadcast, you should override the raw transaction's `v`, `r`, and `s` value with the one returned from the ledger library (so they contain actual signature values).

**Comment by nmajor25** [comment]
@eswak could you post the rest of your code where you broadcasted the signed transaction to the network? I am having similar issues with creating, signing, and broadcasting an ethereum transaction.

**Comment by eswak** [comment]
Hi @nmajor25 here is the full relevant part of the code, it is an angular 1.5 controller function.
```js
$scope.askSignEtherTransaction = function askSignEtherTransaction() {
  var raw = {
    nonce: '0x' + Number($scope.data.nonce).toString(16),
    gasPrice: '0x' + (Number($scope.data.gasPrice) * 1000000000).toString(16),
    gasLimit: '0x' + Number($scope.data.gasLimit).toString(16),
    to: $scope.data.to.toLowerCase(),
    value: '0x' + (Number($scope.data.txValue) * 1000000000000000000).toString(16),
    chainId: 1,
    r: '0x00',
    s: '0x00',
    v: '0x01', // main net
    data: ''
  };
  var txToSign = new ethereumjs.Tx(raw).serialize().toString('hex');

  new ledger.eth(comm).signTransaction_async(path, txToSign).then(function(result) {
    raw.r = '0x' + result.r;
    raw.s = '0x' + result.s;
    raw.v = '0x' + result.v;
    var txSigned = new ethereumjs.Tx(raw);
    txSigned._chainId = raw.chainId;
    txSigned._senderPubKey = $scope.data.publicKey;

    $scope.data.txRaw = raw; // for display purpose
    $scope.data.txSigned = '0x' + txSigned.serialize().toString('hex');

    $scope.$apply();
  }).catch(function() {});
};
```
Then I display a button that links to `https://etherscan.io/pushTx?hex={{data.txSigned}}` and when the user clicks on it he goes to etherscan where they have an util to broadcast the transaction.

hope it helps, lemme know by @mention if something is still unclear
