### ISSUE TITLE
hw-app-eth: signTransaction  different address than given path 

### ISSUE THREAD

**Issue by picatextra** [LedgerHQ/ledgerjs#436]
When decoding the raw transaction , the _from_ value is different than the address of the given path .
Resulting in an error when calling web3.eth.sendSignedTransaction 
(Returned error: insufficient funds for gas * price + value)
Because the signed address is else.

    const txParams = {
        gasPrice: price,
        gasLimit: limit,
        to: ADDR,
        data : data1,
        value: '0x00',
        nonce: web3.utils.toHex(count)
    };
    const txHex = new Transaction(txParams).serialize().toString("hex");
    const result = await appeth.signTransaction("44'/60'/0'/0/0", txHex);

    txParams.r = '0x'+result.r;
    txParams.s = '0x'+result.s;
    txParams.v = '0x'+result.v;
    const tx2 = new Transaction(txParams);

    var serializedTx = '0x' + tx2.serialize().toString('hex');
    let sender  =    web3.eth.accounts.recoverTransaction(serializedTx);

**Comment by picatextra** [comment]
sender different than address at 44'/60'/0'/0/0,  @gre please help

**Comment by ensete** [comment]
HI @picatextra, can I ask you how do you resolve this issue back then, I'm currently facing exactly the same issue without any clue about it. It's indeed strange with different address returned from given path.

**Comment by Git-on-my-level** [comment]
Hey @picatextra how did you fix this? I'm running into the same issue. Any insight would be helpful!

**Comment by Git-on-my-level** [comment]
I solved this by setting the EIP155 bits
https://github.com/LedgerHQ/ledgerjs/blob/423a48f126cc2dc860a5de548dcae160db453735/packages/web3-subprovider/src/index.js#L125
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md
```
// Set the EIP155 bits
tx.raw[6] = Buffer.from([networkId]); // v
tx.raw[7] = Buffer.from([]); // r
tx.raw[8] = Buffer.from([]); // s
```
