### ISSUE TITLE
provideERC20TokenInformation fails when token uses fewer than 18 decimals

### ISSUE THREAD

**Issue by SteveMieskoski** [LedgerHQ/ledgerjs#438]
Hi,
It appears that provideERC20TokenInformation throws `TransportStatusError: Ledger device: Invalid data received (0x6a80)` when attempting to send a token that uses fewer than 18 decimals.  

Just found out that this is not working while trying to send USDT (6 decimals) and was able to reproduce the same error using MCO (8 decimals) as well.

We have it implemented like so:
` const tokenInfo = byContractAddress('0x' + tx.to.toString('hex') );`
`if (tokenInfo) await this.ledger.provideERC20TokenInformation(tokenInfo);`

![Screenshot from 2020-01-09 12-17-21](https://user-images.githubusercontent.com/19334138/72101706-331cb480-32da-11ea-9903-6cecc881a1cf.png)

![Screenshot from 2020-01-09 12-18-04](https://user-images.githubusercontent.com/19334138/72101762-534c7380-32da-11ea-8c6c-4fee783ea2f0.png)

**Comment by gre** [comment]
I'm pretty sure sending token with low decimals works because we support many on Live.
USDT definitely works.

could you either share all APDUs that lead to an error or provide us a way to reproduce the problem? Thanks

**Comment by SteveMieskoski** [comment]
To reproduce you can go to MyEtherWallet.com and attempt to send a token
that has fewer than 18 decimals.
I found the behavior surprising, and it was especially unexpected as you
guys do handle them via Live.  Also, how do you guys handle the transport
for live?  We are using u2f or webusb (depending on whether or not the
browser a user is on supports webUsb).

I'm taking the APDU as the content of the data field created by a call to
`byContractAddress`

MCO
[3, 77, 67, 79, 182, 59, 96, 106, 200, 16, 165, 44, 202, 21, 228, 75, 182,
48, 253, 66, 216, 209, 216, 61, 0, 0, 0, 8, 0, 0, 0, 1, 48, 68, 2, 32, 60,
3, 101, 208, 81, 210, 198, 153, 233, 78, 81, 122, 17, 191, 247, 34, 8, 25,
199, 104, 178, 32, 246, 250, 107, 111, 32, 216, 236, 17, 84, 204, 2, 32,
67, 131, 31, 28, 59, 89, 92, 42, 6, 17, 240, 187, 34, 163, 141, 10, 81, 35,
17, 148, 250, 118, 248, 124, 83, 54, 6, 98, 137, 67, 182, 139]

USDT
[4, 85, 83, 68, 84, 218, 193, 127, 149, 141, 46, 229, 35, 162, 32, 98, 6,
153, 69, 151, 193, 61, 131, 30, 199, 0, 0, 0, 6, 0, 0, 0, 1, 48, 68, 2, 32,
84, 63, 106, 220, 211, 188, 89, 148, 174, 213, 111, 231, 16, 71, 122, 21,
47, 81, 8, 47, 142, 48, 243, 87, 74, 44, 234, 17, 211, 82, 33, 191, 2, 32,
114, 142, 248, 196, 66, 48, 221, 92, 8, 11, 203, 196, 192, 240, 163, 217,
65, 156, 144, 203, 153, 105, 158, 81, 126, 142, 179, 191, 143, 239, 81, 144]
