### ISSUE TITLE
Scan accounts from device in React app using hw-transport-u2f.

### ISSUE THREAD

**Issue by wAISw** [LedgerHQ/ledgerjs#447]
Hello! 
I did some research in your desktop application and I found a method:
```
bridge.scanAccountsOnDevice(mainCurrency, devicePath),
```
this method returns information about accounts on the device, like this:
![image](https://user-images.githubusercontent.com/5791100/72803949-652a0100-3c60-11ea-8429-d21da6372a36.png)

The question is: Can I get this information from the device in react web application using hw-transport-u2f bridge?

I know about bitcoin wiki https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki but if I choose that way I will have to create the backend.

**Comment by gre** [comment]
Unfortunately, this is beyond ledgerjs scope.
the code you have found is not ready to be run in a web application.
I don't think we have this covered in a library so you will have to reimplement this part.

**Comment by wAISw** [comment]
Thank you!
