### ISSUE TITLE
EOS AppConfiguration fetch error with TransportWebHID 

### ISSUE THREAD

**Issue by dev-sk-master** [LedgerHQ/ledgerjs#450]
Can below code be used to fetch EOS public key from Ledger Nano S.
Browserified version of @ledgerhq/hw-transport-webhid and @ledgerhq/hw-app-eth

var transport = await TransportWebHID.create(); 
var eos = new AppEth(transport);

Device permission and connect works but when trying to get app config it generates error.
eos.getAppConfiguration()

name: "DisconnectedDeviceDuringOperation", message: "Failed to write the report."

![error](https://user-images.githubusercontent.com/11884551/72961526-56b22580-3dd7-11ea-8afc-232d0b00e4f6.png)

**Comment by gre** [comment]
please report to EOS app authors ( which i think is https://github.com/tarassh/eos-ledger )
