### ISSUE TITLE
[webusb] Nano X not detected on Windows 10 

### ISSUE THREAD

**Issue by picatextra** [LedgerHQ/ledgerjs#456]
On Windows , if i want to connect to my Nano X through webusb, it's not showed on the browser popup. I noticed Windows don't find a driver for the device, while Nano S has a driver.
On Mac, it's ok.

Command line to show usb device :
`navigator.usb.requestDevice({filters:[{ vendorId:0x2c97}]})`

**Comment by cacampbell** [comment]
Hey M8, 

WebUSB is only _kindof_ supported on windows, and requires some manipulation with Zadig to get it to work. 

Here is how we construct the transport for all platforms:

```
   private async getTransport(): Promise<Transport> {
        // Support NodeHID for Electron

        if (this.transport != null) {
            return this.transport;
        }

        // WebHID should be what we're doing but it's still unstable on Chrome
        const shouldUseWebHid = false;

        // WebUSB is *supposed* to work on Windows (and Opera?), but alas
        const webusbSupported =
            await TransportWebUSB.isSupported() &&
            platform.os!.family !== "Windows" &&
            platform.name !== "Opera";

        if (shouldUseWebHid) {
            this.transport = await TransportWebHID.create(
                OPEN_TIMEOUT,
                LISTENER_TIMEOUT
            );
        } else if (webusbSupported) {
            this.transport = await TransportWebUSB.create(
                OPEN_TIMEOUT,
                LISTENER_TIMEOUT
            );
        } else {
            this.transport = await TransportU2F.create(
                OPEN_TIMEOUT,
                LISTENER_TIMEOUT
            );

            // U2F requires a pre-negotiated scramble key
            // Don't steal this
            this.transport.setScrambleKey("XXXX");
        }

        return this.transport!;
    }
```

**Comment by picatextra** [comment]
Ok but Nano S is working well in the same env.

**Comment by picatextra** [comment]
Looks like it's working now, i didn't change any of my code.

**Comment by humanumbrella** [comment]
Hi @picatextra - just wondering:  Can you interact with the device (Nano X) more than just once on Windows? 

I am seeing one normal interaction and then `Invalid Channel` error and the device drops out to the App List. I haven't investigated further yet but wanted to know if things seem normal on your end?

**Comment by picatextra** [comment]
@humanumbrella , i had somes transactions, didn't have any error
