### ISSUE TITLE
Help on my ionic-hw-transport-ble implementation

### ISSUE THREAD

**Issue by Jmunapo** [LedgerHQ/ledgerjs#459]
`https://github.com/Jmunapo/ionic-hw-transport-ble`

Thanks for the great libraries.
I'm here because for days I've been trying to create a Transport for `ionic 4` using the cordova bluetoothLE plugin with no luck.

I'm stuck on this `@ledgerhq/hw-transport-web-ble` method
```
  async inferMTU() {
    let mtu = 23;
    await this.exchangeAtomicImpl(async () => {
      try {
        mtu =
          (await merge(
            this.notifyObservable.pipe(
              first(buffer => buffer.readUInt8(0) === 0x08),
              map(buffer => buffer.readUInt8(5))
            ),
            defer(() => from(this.write(Buffer.from([0x08, 0, 0, 0, 0])))).pipe(
              ignoreElements()
            )
          ).toPromise()) + 3;
      } catch (e) {
        log("ble-error", "inferMTU got " + String(e));
        this.device.gatt.disconnect();
        throw e;
      }
    });

    if (mtu > 23) {
      const mtuSize = mtu - 3;
      log(
        "ble-verbose",
        `BleTransport(${String(this.id)}) mtu set to ${String(mtuSize)}`
      );
      this.mtuSize = mtuSize;
    }

    return this.mtuSize;
  }

```

which I can't figure out how it works.
If anyone can explain to me or check out my Github repo on
[ionic-hw-transport-ble](https://github.com/Jmunapo/ionic-hw-transport-ble) for the source code and more details

**Comment by gre** [comment]
When sending (on write channel) 0800000000 to the device, it answers (on notify channel) with 0800000000nn where nn is the MTU size.

The MTU size is the maximum number the hardware will support for communication and chunking the apdu packets so it's quite important for performance to establish it. It defaults to 20.

In our current logic getting the MTU is also they way we use to trigger the bondings (in fact any write to the channel will trigger it if devices don't know each other) and based on that to succeed we assume it succeed.

> Side note: In the general logic that uses that method you will see that we need to disconnect just after a pairing (which is determined by the timing of that infermcu). Disconnect is currently necessary for the nano x device to remember the bondings.
