### ISSUE TITLE
An action was already pending on the Ledger device. Please deny or reconnect.

### ISSUE THREAD

**Issue by DalderupMaurice** [LedgerHQ/ledgerjs#461]
Hi!

I am trying to implement a web application, which supports the Ledger, but I get the following error when I try to implement it.

Error: An action was already pending on the Ledger device. Please deny or reconnect.

Code used:
```js
import Transport from "@ledgerhq/hw-transport-webusb";

// Request access: 
await Transport.create();

// Web request is allowed and a device was selected at this point
const paths = await Transport.list();
const device = await Transport.open(paths[0]);

// Params to retrieve a NEO public key
const result = await device.send(
  cla, // 128
  ins, // 4
  p1, // 0
  p2, // 0
  Buffer.from(data, "hex"), // Buffer(20) [128, 0, 0, 44, 128, 0, 3, 120, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  statusList // [36864]
);
  
return results;
```

I also tried using the transport instance returned from `Transport.create`, but this gave the same issue.

Side note - quite irrelevant:
I must also notice that ` const device = await Transport.openConnected();` doesn't work for Typescript as the community typings named it incorrectly (openConnection instead of openConnected)

**Comment by gre** [comment]
``` 
await Transport.create();
const paths = await Transport.list();
const device = await Transport.open(paths[0]);
```

first of all I'm not sure to understand why you need to do all of these. It's 3 times the same thing.

create() is actually equivalent of doing list/listen() and then open() so you should be good by just doing `const device = await Transport.create()`


The error itself means that somewhere in your code there are two concurrent send() that are done and without awaiting the previous one to be done.

**Comment by DalderupMaurice** [comment]
Thanks for the reply @gre 
& In reality the code is split into 3 actions.

I use the `Transport.create()` to trigger the popup for users to allow/select a device in the browser. (I could also use the .request() here indeed)

After that, I poll the `Transport.list` to detect when devices are removed/added (as I was not able to get the listen function working properly together with redux as somehow it unsubscribed after 1 device was added/removed)

Lastly, the found device of the `Transport.list` function is passed on to the action to open the device and trigger the send action.. but I fail to see any concurrent send() operations as they are only fired once.

However, I am currently not able to have another look at the code today and will check back later this week, taking your comments into consideration.
