### ISSUE TITLE
INS_NOT_SUPPORTED — what is INS short for?

### ISSUE THREAD

**Issue by everdimension** [LedgerHQ/ledgerjs#463]
Hi!

I'm getting this error and I wonder what this abbreviation stands for.
In code it's only found here: https://github.com/LedgerHQ/ledgerjs/blob/a52b16d8f5f3ddd5ac1f023ee30efcf22acc9b9e/packages/errors/src/index.js#L255

And while we're here, I think it would be a good thing to avoid abbreviations and (at least in code comments) write full names for other error codes, too.

**Comment by gre** [comment]
this is part of the APDU protocol. binary packets  have CLA, INS, P1, P2, data.. in the spec.

https://en.wikipedia.org/wiki/Smart_card_application_protocol_data_unit

INS stands for Instruction code.

I think it's at least better to have INS_NOT_SUPPORTED than 0x6d00 , but I agree we could make it more obvious.

**Comment by qiluge** [comment]
So what are the meanings of the codes of CLA and INS at Ledger?

**Comment by gre** [comment]
> So what are the meanings of the codes of CLA and INS at Ledger? I saw a CLA code 0xe0, INS code has 0x01, 0x04, 0x08 etc.

I recommend to look at the documentation of each app.
each app can define their own commands and should document them.

examples

- https://github.com/LedgerHQ/ledger-app-btc/blob/master/doc/btc.asc
- https://github.com/LedgerHQ/ledger-app-eth/blob/master/doc/ethapp.asc

more documentation should be provided in the future.

**Comment by qiluge** [comment]
why zilliqa APP have not this doc...

**Comment by gre** [comment]
this is not in scope of ledgerjs repository, ask directly on the app project owners.
