### ISSUE TITLE
How to prepare the data/erc20.js file

### ISSUE THREAD

**Issue by JasonHJ** [LedgerHQ/ledgerjs#465]
I want to show token's information on ledger when transfering tokens, so how to prepare the data like the erc20.js.  ( 'ledgerjs/packages/hw-app-eth/data/erc20.js')
What does each field of the following data represent?
["ethereum","1irst","FST",6,"1irst","304402202e2c1788729182a680d9f1ca5fcc00a7dd176155701e9ac4055f80b71e4bfa5a02206cbcd1634796277f852cda36271259d2d89c13f60e15402b1f4e68a6cbd8e381","0x310c93dfc1C5E34CDF51678103f63C41762089CD",false,false]

**Comment by gre** [comment]
In ledgerjs, the file data/erc20 is a [base64 encoded blob of an array of `Buffer.from([ticker.length]), ticker, contractAddress, decimals,  chainId, signature`](https://github.com/LedgerHQ/ledgerjs/blob/master/script/crypto-assets-importer/importers/erc20.js) which is essentially the same signature as what the device needs.

This data is currently only distributed to address one specific problem: the Ledger device needs a Ledger signature proof that a given erc20 with a specific contract is associated to a specific ticker and with a magnitude. This is essentially what the erc20.js file of `@ledgerhq/hw-app-eth` have.

you seem to refer the data we have in live-common which is another library that we use for Ledger Live. It have a tiny bit more information but probably a bit specific to us (at Ledger) (like the name, and if the Live support list that currency / have a countervalues). This function give a better idea of what the fields are in the array structure: https://github.com/LedgerHQ/ledger-live-common/blob/master/src/families/ethereum/tokens.js#L10-L39
