### ISSUE TITLE
Every call to getWalletPublicKey requires a physical approval on the device

### ISSUE THREAD

**Issue by borxes** [LedgerHQ/ledgerjs#474]
Hi, when I use ledger with a web app (hw-transport-u2f), it asks for a physical approval every time that getWalletPublicKey() is called ("Export public key?" on the device display).

It doesn't work this way from Node.js using hw-transport-node-hid. How can I make the ledger to be more user friendly and not ask for public key permission when accessing it from the web?

**Comment by gre** [comment]
This is a U2F security measure, U2F does not require any permission on the browser so any website can run commands to the device.

I recommend to switch to webusb or webhid.
