### ISSUE TITLE
Microsoft Edge fatal javascript syntax error

### ISSUE THREAD

**Issue by jlopp** [LedgerHQ/ledgerjs#477]
We're testing adding support for more transport layers to our web app's signing page and are having difficulty with the latest version of Edge. In particular, it throws a fatal error:

SCRIPT1028: Expected identifier, string or number

At this part of the devices js: https://github.com/LedgerHQ/ledgerjs/blob/bdeeea2a74f7f1ab295db545a273ef004a92850a/packages/devices/src/index.js#L124

In particular, Edge seems to dislike the "...spec" syntax.

We've played around a bit with our webpack config but can't see what it could be screwing up; we are using it with babel presets ("@babel/preset-env")

Has anyone else reported issues with Edge?

**Comment by gre** [comment]
Hi @jlopp :)

the `src` folder of each package under `packages/*` are source files that generates, through babel, a `lib` folder (when running `yarn` at the top level of this project). Only the lib folder should be guaranteed be preprocessed back into a more supported version of JavaScript and it should be recognized even on Edge.

The libraries are pushed to NPM and if you import it from `@ledgerhq/devices` the entry point should be lib/index.js and it should work fine.

on this URL: (which a service that "reverse" a npm package)

https://unpkg.com/browse/@ledgerhq/devices@5.11.0/lib/index.js

we can see that the lib/index.js (L138) essentially have transpiled that code to

```js
_objectSpread({ deviceModel }, spec);
```

Alternatively if you are looking at including the libraries without using NPM, you could grab the lib folder and it should work fine.

Hope this helps.

**Comment by jlopp** [comment]
Gotcha; it's an issue with our project's transpiler - sorry to bother you!
