### ISSUE TITLE
@ledgerhq/hw-transport-node-hid not working on Electron

### ISSUE THREAD

**Issue by matextrem** [LedgerHQ/ledgerjs#480]
I'm using @ledgerhq/hw-transport-node-hid 5.11.0 in electron, but when I require it and start the app by running electron . it stucks at the require statement without showing any error in console.

Here is my code:

**preload.js**

```
const TransportNodeHid = require("@ledgerhq/hw-transport-node-hid").default;
window.TransportNodeHid = TransportNodeHid;
```

"electron": "^7.1.10",
"@ledgerhq/hw-transport-node-hid": "5.11.0",

**Node Version**: v10.16.3

Did I miss anything?

**Comment by gre** [comment]
Where are you running that code? On the chromium thread? Main thread?

**Comment by matextrem** [comment]
I’m running it in the preload.js script of my browser window in order to expose the TransportNodeHid in the window object so that I can send this value to the [Onboardjs](https://docs.blocknative.com/onboard) library in my react app. 


https://github.com/blocknative/onboard/releases/tag/1.3.6

**Comment by gre** [comment]
i'm afraid node-hid likely doesn't work there then. and it's highly not recommended to do so (blocking the UI), usb blocking sometimes for a non negligible time. 

in Ledger Live Desktop what we do is we fork our own process from main thread and we have the device logic inside it. there are more ideas to build around it like proxying the apdus to a process but I don't think node-hid is meant to work in Electron chromium context

**Comment by matextrem** [comment]
preload script runs before chromium app and runs over nodeJS. I could replicate the error. It seems to be a problem with the node-usb package

https://github.com/tessel/node-usb/issues/350

I managed to fix it by doing a fresh install but it comes up again when you install another dep.

**Comment by gre** [comment]
this makes no sense, we don't depend on `node-usb` but on `node-hid`

**Comment by matextrem** [comment]
It does makes sense at all. You are using the usb package in the library.
