### ISSUE TITLE
TypeError: Btc is not a constructor

### ISSUE THREAD

**Issue by ambush276** [LedgerHQ/ledgerjs#485]
tried updating to using ES6 style of js... still having this issue.

node v12.16.1

@ledgerhq/hw-app-btc@5.12.0

@ledgerhq/hw-transport-node-hid@5.12.0

snippet of code

import regeneratorRuntime from "regenerator-runtime";
import Btc from "@ledgerhq/hw-app-btc";
import tport from "@ledgerhq/hw-transport-node-hid";

getBtcAddress = async () => {
  const getTransport = () => tport.create();
  const btc = new Btc(getTransport);
......
};

getBtcAddress().then(a => a).catch(error => console.log(error +"\n Got in ERROR REJECTION"));

**Comment by gre** [comment]
usage example: https://github.com/LedgerHQ/ledgerjs-examples/blob/master/basic-u2f-react/index.js#L16-L18

Btc takes a transport, not a function that get a transport.

**Comment by ambush276** [comment]
changed to ``` const getTransport = await tport.create(); ```

also tried with 

```
import TransportU2F from "@ledgerhq/hw-transport-u2f";
const getTransport = await TransportU2F.create(); ```


still getting the same error: 

"TransportU2F.create is not a function"
or
"tport.create is not a function"

**Comment by gre** [comment]
I think it might be due to the compiler you are using, webpack? babel?
did you try to console.log(TransportU2F) ?

**Comment by ambush276** [comment]
i installed using npm and node node v12.16.1

output of console.log(TransportU2F)

```
{
  default: [Function: TransportU2F] {
    isSupported: [Function],
    list: [Function],
    listen: [Function]
  }
}
```

**Comment by gre** [comment]
there is something weird in your bundler to me. It's not correctly implementing "ES modules"

you can attempt this:

    import { default as TransportU2F } from "@ledgerhq/hw-transport-u2f";

like you would do

    const { default: TransportU2F } = require("@ledgerhq/hw-transport-u2f");

even tho default is supposed to be what is imported by ... _default_.
