### ISSUE TITLE
serializeTransactionOutputs is not a function in @ledgerhq/hw-app-btc:5.3.0

### ISSUE THREAD

**Issue by VDamas** [LedgerHQ/ledgerjs#506]
After release @ledgerhq/hw-app-btc:5.3.0 the function serializeTransactionOutputs is missing.
What alternative there is to generate outputScript ?

**Comment by VDamas** [comment]
Wrong repo

**Comment by gre** [comment]
You should be able to import it like this:

```
import { serializeTransactionOutputs } from "@ledgerhq/hw-app-btc/lib/serializeTransaction"
```
