### ISSUE TITLE
TransportU2F 'remove' event

### ISSUE THREAD

**Issue by aaronbarnardsound** [LedgerHQ/ledgerjs#510]
Is there a way to detect when a user has disconnected their Ledger device when connected via the `@ledgerhq/hw-transport-u2f` transport?

I have tried listening with an observer like this:

```javascript
const observer = {
  next: (event: any) => {
    if (event.type === 'remove') {
      console.log('User disconnected device')
    }
  },
  error: () => {},
  complete: () => {}
}

TransportU2F.listen(observer)
```

This works as expected when using the `@ledgerhq/hw-transport-node-hid` package for Electron apps, but when using with the `@ledgerhq/hw-transport-u2f` package for browsers, only an `event.type` of `'add'` is ever fired.

I have also tried listening for a `'disconnect'` event on the created transport and that doesn't fire either.

**Comment by gre** [comment]
No there is no way. The u2f protocol does not offer it unfortunately.
