### ISSUE TITLE
[hw-app-btc] - after v5.3.0 refactor, missing `serializeTransactionOutputs` as function

### ISSUE THREAD

**Issue by humanumbrella** [LedgerHQ/ledgerjs#512]
Try to run the example code with v5.17.0 and you see what I mean:

> /**
>   @example
> const tx1 = btc.splitTransaction("01000000014ea60aeac5252c14291d428915bd7ccd1bfc4af009f4d4dc57ae597ed0420b71010000008a47304402201f36a12c240dbf9e566bc04321050b1984cd6eaf6caee8f02bb0bfec08e3354b022012ee2aeadcbbfd1e92959f57c15c1c6debb757b798451b104665aa3010569b49014104090b15bde569386734abf2a2b99f9ca6a50656627e77de663ca7325702769986cf26cc9dd7fdea0af432c8e2becc867c932e1b9dd742f2a108997c2252e2bdebffffffff0281b72e00000000001976a91472a5d75c8d2d0565b656a5232703b167d50d5a2b88aca0860100000000001976a9144533f5fb9b4817f713c48f0bfe96b9f50c476c9b88ac00000000");
> const outputScript = btc.serializeTransactionOutputs(tx1).toString('hex');
>   */

output/error: 

> `btc.serializeTransactionOutputs is not a function`

Runs fine up to v5.3.0 which is when a large refactor of the app happened. Missing an export / import?

view console ... 
OK --> u2f + hw-app-btc@5.2.0 --> https://9vwbs.csb.app/
!OK --> u2f + hw-app-btc@5.17.0 --> https://6wmnj.csb.app/

Thanks in advance.

**Comment by gre** [comment]
this function has moved to

```
import { serializeTransactionOutputs } from "@ledgerhq/hw-app-btc/lib/serializeTransaction"
```

this function is a pure function and it makes not much sense it was in a "btc instance", it doesn't need the transport or do anything with the device.

i'll still add a note to forward this function (with a deprecated message)
