### ISSUE TITLE
[WebUsb] Unable to reset the device

### ISSUE THREAD

**Issue by picatextra** [LedgerHQ/ledgerjs#543]
Since Chrome version 87, it's impossible to connect through USB.
device.reset() always returns  "Unable to reset the device"
Also the browser popup to select devices doesn't show up.

**Comment by gre** [comment]
Hi @picatextra , thanks for the Github issue.

- https://github.com/LedgerHQ/ledgerjs/pull/545 this fix might help. if you have the opportunity to test on your side, we would appreciate if you could confirm that it indeed will fix it.
- in any case, I think @meriadec is on the good track on fixing it via this PR and we will consider merging it and delivering a new release before the end of this week.

Thanks

**Comment by gre** [comment]
https://github.com/LedgerHQ/ledgerjs/pull/545
v5.34.1 should have fixed it
