### ISSUE TITLE
Cannot read property 'getDevices' of undefined

### ISSUE THREAD

**Issue by antonioribeiro** [LedgerHQ/ledgerjs#556]
### My environment

Chrome Version 87.0.4280.88 (Official Build) (x86_64)
Safari Version 14.0 (15610.1.28.1.9, 15610)
MacOS Catalina 10.15.7 (19H2)
NodeJS v14.7.0
NPM version 6.14.7
Webpack version 4.44.2
Stellar Account Viewer: connects fine via USB
Albedo: also connects fine and shows account as `Ledger m/44'/148'/0'`

### Problem
On Chrome I get this error while trying to create the transport:

```
message: "Cannot read property 'getDevices' of undefined"
name: "TransportOpenUserCancelled"
```

On Safari the error is: 

```
Unhandled Promise Rejection: TransportOpenUserCancelled: undefined is not an object (evaluating 'navigator.usb.getDevices')
```
Here's part of the code related 

``` javascript
import StellarApp from '@ledgerhq/hw-app-str'
import TransportWebUSB from '@ledgerhq/hw-transport-webusb'

TransportWebUSB.create().then((transport) => console.log(transport)) // errors here
```

Orignally code was using async/await

``` javascript
const getVersion = async () => {
    const transport = await TransportWebUSB.create() // errors here

    const stellarApp = new StellarApp(transport)

    ...
}
```

**Comment by gre** [comment]
Safari do not support webusb therefore the library currently produces this error.

If you want, you can have a bit more "defensive programming" style with this code approach:

```js
if (TransportWebUSB.isSupported()) {
  ... transport code here...
}
```

**Comment by antonioribeiro** [comment]
Nice, @gre , thanks!
But I'm actually using Chrome (first line of my environment above). Safari was just to double check

**Comment by antonioribeiro** [comment]
@gre , `isSupported()` is resulting in false on Chrome, probably because it also uses `getDevices()`, which is erroring, as per the above error messages:

``` javascript
export const isSupported = (): Promise<boolean> =>
  Promise.resolve(
    !!navigator &&
      // $FlowFixMe
      !!navigator.usb &&
      typeof navigator.usb.getDevices === "function"
  );
```

**Comment by aditim121** [comment]
@gre, I am also getting the same error
![Screenshot from 2021-01-05 15-19-00](https://user-images.githubusercontent.com/60029999/103631874-8c5d0980-4f69-11eb-86ae-5c0498e5ad48.png)

added below code as well to check if its supported in chrome or not: It says as supported.
if (TransportWebUSB.isSupported()) {
      console.log("supported")
    }else{
      console.log("not supported")
    }
    
Also, when clicking on "Connect with USB" the error comes on console and the dialog box to detect the device does not open.

**Comment by gre** [comment]
This is weird:

on my end
```js
    !!navigator &&
      // $FlowFixMe
      !!navigator.usb &&
      typeof navigator.usb.getDevices === "function"
```
yields `true`.

And i'm also on `Version 87.0.4280.88 (Build officiel) (x86_64)` under `Mac OS Catalina`.
 
 This was enabled in my side in chrome://flags/

![Capture d’écran 2021-01-05 à 11 38 31](https://user-images.githubusercontent.com/211411/103636654-94f21780-4f4a-11eb-816b-213cada602eb.png)

**But even after disabling it, I still obtain `true`.** 😕

**Comment by aditim121** [comment]
Worked for me.
Silly thing, didn't notice.
Just added "https" to the server and it worked.

**Comment by antonioribeiro** [comment]
Sorry, @gre , my problem was the same of @aditim121.

So for reference if anyone else gets here: you need to run a secure app and serve it via port 443, having at least a self-signed certificate working on it.

Thank you!

**Comment by gre** [comment]
Ok it's good to know. Sad that the behavior of chrome is really weird. I think it used to throw a Security error or something like that..
