### ISSUE TITLE
No WebUSB interface found for your Ledger device when creating transport using React Redux

### ISSUE THREAD

**Issue by yuchenBalloonbox** [LedgerHQ/ledgerjs#566]
I am trying to build a Ledger React app with '@ledgerhq/hw-transport-webusb' based on an open-source project.

The initialize method is included in the Redux, code as follows:

```
export const fetchLedgerStellarAddressAction = createAsyncThunk<
  { publicKey: string },
  string,
  { rejectValue: RejectMessage }
>(
  "walletLedger/fetchLedgerStellarAddressAction",
  async (bipPath, { rejectWithValue }) => {
    const result = { publicKey: "" };
    try {
      const transport = await TransportWebUSB.create();
      const ledgerApi = new LedgerApi(transport);
      const response = await ledgerApi.getPublicKey(bipPath);
      result.publicKey = response.publicKey;
    } catch (error) {
      return rejectWithValue({ errorString: error.toString() });
    }
    return result;
  },
);
```

When trying to connect the actual Ledger Device to the app, an error shows  -> **TransportInterfaceNotAvailable: No WebUSB interface found for your Ledger device. Please upgrade firmware or contact tech support.**

According to the README for transport webusb, 

```
FAQ: "DOM Exception" is triggered when creating the transport
The transport functions create() and listen() must be called in the context of an user interaction (like a "click" event), otherwise it fails with DOM Exception. This is by WebUSB design. You also must run on HTTPS.
```

I assume I have to wrap the try-catch block showed above inside an event listener.

```
try {
      const transport = await TransportWebUSB.create();
      const ledgerApi = new LedgerApi(transport);
      const response = await ledgerApi.getPublicKey(bipPath);
      result.publicKey = response.publicKey;
    } catch (error) {
      return rejectWithValue({ errorString: error.toString() });
    }
```

I just wonder if anyone has any idea on how I could do that, or how I could solve this bug without updating the firmware?

PS: 
Fireware version: 
- Secure Element: 1.6.1
- Microcontroller: 1.12
- Bootloader: 0.11
-

**Comment by gre** [comment]
I'm afraid it's not a bug but a security restriction of the webusb / webhid transport:
It's only allowed to open a web usb transport in the context of a click, otherwise you get a DOM exception. This is what Chrome put in ace to guarantee a web app don't access user's devices without user consent (in context of clicking a "connect a device" for instance)

Please see https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-transport-webusb#faq-dom-exception-is-triggered-when-creating-the-transport

**Comment by quietbits** [comment]
@gre I hope it's OK to ask a related question on this thread. I'm getting the same error when trying to connect to Ledger with the Stellar app open (it's fine if I haven't opened the app yet). Is that expected?

With this flow, the user will have a two-step sign in 1) connect the Ledger device, 2) open the app to get the account information, which is not great. With U2F it works with the Stellar app open.

Here's a very simple example to demonstrate the connect part: [https://codesandbox.io/s/ledger-webusb-hp1on?file=/src/index.js](https://codesandbox.io/s/ledger-webusb-hp1on?file=/src/index.js).

Thank you!
