### ISSUE TITLE
errorCode: 1, errorMessage: "device status code: -3

### ISSUE THREAD

**Issue by wannabit-jayb** [LedgerHQ/ledgerjs#60]
Hi, I am using this LedgerHQ API to develop our platform.

Similar to Ethereum, which enables users to exchange tokens from one another, 

we are working on coins that have similar platform.

Right now, I have been testing Qtum for weeks to make token transaction.

**However, I believe there is a bug when signing a transaction (the source code below shows where triggers an error).**

When we tested to create and sign token transaction for the first time, it was sent well, but the second time using the same Qtum address it triggers this specific error. (We waited until the transaction has enough confirmations, so it shouldn't be about confirmations)

`{errorCode: 1, errorMessage: "device status code: -3"}`

```
u2f.responseHandler_ = function(message) {
 console.log("u2f.responseHandler_", message);
 var response = message.data;
 var reqId = response['requestId'];
 if (!reqId || !u2f.callbackMap_[reqId]) {
   console.error('Unknown or missing requestId in response.');
   return;
 }
 var cb = u2f.callbackMap_[reqId];
 delete u2f.callbackMap_[reqId];
 cb(null, response['responseData']);
};
```

The specific test-case as explained above, it works well in my local computer using node commands. However, like I attached the source code that test-case does not work in browser (u2f). It is really odd. 

Do you think this is a bug? 

or

Do you think there is something I am missing?

Versions we have tried are as below

> v1.1.3

> v2.1.3

**Comment by CQZW** [comment]
me to ,did have sl  it?

**Comment by wannabit-jayb** [comment]
@CQZW what do you mean by sl it?

**Comment by CQZW** [comment]
Have you solved this problem?

**Comment by CQZW** [comment]
@wannabit-jayb 

Have you solved this problem?

**Comment by wannabit-jayb** [comment]
@CQZW 
Nope, are you having the same problem?

**Comment by CQZW** [comment]
@wannabit-jayb 
yes. Can you give me a way of contact? skype?..

**Comment by wannabit-jayb** [comment]
@CQZW 
When does that error specifically trigger on your case? 
There is not much to discuss on skype if we are having the same issue.

**Comment by gre** [comment]
Should be fixed. We need apdu example to reproduce if not the case
