### ISSUE TITLE
Problem with WebUSB + Chrome 91.X

### ISSUE THREAD

**Issue by humanumbrella** [LedgerHQ/ledgerjs#607]
Mostly an FYi as I am still searching for answers.

After updating to Chrome 91, when attempting to connect to either Ledger device (X or S), I am seeing the opportunity to pair the device as normal, what looks like a successful pairing, but then when I try to do any operation, I am getting `The device was disconnected.`

This is for existing applications that work fine on Chrome 90.X.

**Comment by humanumbrella** [comment]
Device shows up and appears to be behaving properly in chrome://usb-internals/

Ultimately, I am trying to use `const transport = await TransportWebUsb.create()` - and now this does not work in newest Chromium version or any browser that uses it. It does not seem to matter if I am connecting via a saved (previously paired) device or have reset that and connecting fresh. I get the same outcome. Pasting some output from chrome://device-log/

```
USBUser[13:50:56] USB device added: vendor=11415 "Ledger", product=4117 "Nano S", serial="0001", guid=02b2cba5-69d7-4984-814f-40f524495323

USBEvent[13:50:56] Failed to open device: No such device (it may have been disconnected)

USBUser[13:50:56] USB device removed: guid=7d99e9c9-ff3b-47b4-9281-5a0d0dd14294

USBEvent[13:50:56] Failed to claim interface: Other error

USBUser[13:49:21] USB device added: vendor=11415 "Ledger", product=4117 "Nano S", serial="0001", guid=7d99e9c9-ff3b-47b4-9281-5a0d0dd14294

USBEvent[13:49:20] Failed to open device: No such device (it may have been disconnected)

USBUser[13:49:20] USB device removed: guid=197e5832-548f-43c0-bc7e-b9294581db7b

USBEvent[13:49:20] Failed to claim interface: Other error
```

Any clients that have Chrome auto-update turned on are now affected and unable to use their devices. Please advise.

cc @meriadec as you fixed `hw-transport-webusb` last time.

**Comment by humanumbrella** [comment]
I didn't mention but I already tried to flip the bit in chrome://flags to `NEW USB Backend` to **Disabled** 

It still does not work, the behavior is:

First try - `Unable to claim interface.`
Second try - `The device was disconnected.`

**Comment by humanumbrella** [comment]
Bump - this is a major issue, please advise. I am continuing to debug further. 

Is anyone from Ledger able to assist?

**Comment by MattG561** [comment]
Can confirm that Ledger's WebUSB transport is broken in Chrome version 91 and up. Works with Brave (based on chromium v90) in the meantime. 

Would be really nice if Ledger could implement a fix for their transport. It has been a bit unreliable as of late, especially on Windows machines & newer version of Chrome.

**Comment by MattG561** [comment]
@humanumbrella Are you using the latest version of the WebUSB transport?

**Comment by alexshchur** [comment]
Confirming this issue. [Transport.open method returns promise gets rejected](https://github.com/LedgerHQ/ledgerjs/blob/master/packages/hw-transport/src/Transport.js#L235) with the message  `"index.js:1 Error creating transport: DOMException: The device was disconnected"`.

Right now the only way I was able to find in order to make Ledger work on MacOS now is to use WebHID transport

**Comment by humanumbrella** [comment]
> @humanumbrella Are you using the latest version of the WebUSB transport (5.51.1)?

I have multiple setups, some with latest everything (transport/firmware/btc app) and some not on latest. 

Even with toggling `New USB Backend` I cannot get anything to work as is in Chrome v91.x

**Comment by MattG561** [comment]
> > @humanumbrella Are you using the latest version of the WebUSB transport (5.51.1)?
> 
> I have multiple setups, some with latest everything (transport/firmware/btc app) and some not on latest.
> 
> Even with toggling `New USB Backend` I cannot get anything to work as is in Chrome v91.x

Okay, same here. Hoping Ledger comments on this asap.

**Comment by humanumbrella** [comment]
I wrote here and in their Ledger Devs slack #support channel yesterday. It's getting late on a Friday night in France so I am assuming it will be quiet, but hoping to be surprised!

**Comment by Velenir** [comment]
I made a [sandbox](https://ydx4v.csb.app/) to test connection with different transports:

On Linux (Ubuntu 20.04):

-   Firefox: only U2F is supported and works
-   Chrome 91: Bluetooth not supported, other transports supported but U2F breaks with `Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE`

On Windows:

-   Firefox: only U2F is supported and works
-   Chrome 91: every transport is supported and works, but WebUSB sometimes doesn't connect at first

Can someone try on MacOS please

**Comment by MattG561** [comment]
> I made a [sandbox](https://ydx4v.csb.app/) to test connection with different transports:
> 
> On Linux (Ubuntu 20.04):
> 
> * Firefox: only U2F is supported and works
> * Chrome 91: Bluetooth not supported, other transports supported but U2F breaks with `Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE`
> 
> On Windows:
> 
> * Firefox: only U2F is supported and works
> * Chrome 91: every transport is supported and works, but WebUSB sometimes doesn't connect at first
> 
> Can someone try on MacOS please
 
@Velenir How did you manage to get the WebUSB transport working on Chrome 91? Ledger's docs say that U2F is deprecated on all platforms/transports and should be avoided.

**Comment by Velenir** [comment]
> @Velenir How did you manage to get the WebUSB transport working on Chrome 91? Ledger's docs say that U2F is deprecated on all platforms/transports and should be avoided.

@MattG561 
I didn't do anything particular, didn't flip any browser flags or anything like that. It just worked for me on Windows, Chrome 91.0.4472.77 (Official Build) (64-bit). You can see the code in the sandbox above


https://user-images.githubusercontent.com/5121491/120099625-39b50180-c145-11eb-9314-c37137daec19.mp4
(Don't have a Ledger with bluetooth though)


While U2F is deprecated it's the only transport that is supported on Firefox, so have to use it there.

**Comment by skoold2003** [comment]
I've found that it's not working on Firefox either. It may be unrelated but when I try to connect on V.88.0.1  I get "Uncaught (in promise) Error: navigator.usb is undefined"

**Comment by bkbooth** [comment]
Looks like Brave just updated to Chromium v91, Ledger WebUsb no longer working there either.

@skoold2003 WebUsb never worked in Firefox, it's not supported. If you're talking about U2F, it's still working for me in FF today.

**Comment by 0dayZh** [comment]
We've tried via WebHID and it works.

```JavaScript
const transport = await TransportWebHID.create()
```

**Comment by MattG561** [comment]
> We've tried via WebHID and it works. @humanumbrella
> 
> ```js
> const transport = await TransportWebHID.create()
> ```

Can confirm that WebHID is not working for chrome v90. I am getting a `the device is already open` error when trying to use any BTC app functions.

**Comment by humanumbrella** [comment]
Any help from Ledger on this one, @gre  ?

Obviously based on commentary here there is a major problem in the latest Chrome update regarding WebUSB connection. My team can move to add in support for WebHID, which appears to be working, but would really like to know why WebUSB is not working, especially if it's something trivial. Also, the [ledgerjs README](https://github.com/LedgerHQ/ledgerjs) shows WebHID as experimental, so I am a little hesitant to promote that at the moment.

![Screen Shot 2021-06-01 at 12 56 30 AM](https://user-images.githubusercontent.com/10471648/120287572-353b3680-c274-11eb-9439-b78325dfbcbe.png)

Please advise.

**Comment by gre** [comment]
@humanumbrella I think we have to update this README that do not reflect the technical reality anymore. It's clear that Chrome want to sunset our usage of U2F for bidirectional communication as it was documented in https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md

Right now, both WebUSB and WebHID are in Drafts stages ( https://wicg.github.io/webusb/ and https://wicg.github.io/webhid/ ). WebHID is more and more the direction we would recommend but there is still a ❓  regarding more browser to support it and which technology will be favorized in the future (as soon as these specs leave the Draft phase).

**Comment by humanumbrella** [comment]
@gre - thank you very much for this information! I will proceed with getting our team to include WebHID support.

Can you confirm whether anyone at Ledger can look at this WebUSB problem? I genuinely believe it's something trivial about a timeout or command rate limiting or something. The reason that I believe this is because the browser is fully able to both see and pair with the device (which seems to be the hard part) but then on an attempt at any communication with the device, an error is thrown.

**Comment by MattG561** [comment]
> @gre - thank you very much for this information! I will proceed with getting our team to include WebHID support.
> 
> Can you confirm whether anyone at Ledger can look at this WebUSB problem? I genuinely believe it's something trivial about a timeout or command rate limiting or something. The reason that I believe this is because the browser is fully able to both see and pair with the device (which seems to be the hard part) but then on an attempt at any communication with the device, an error is thrown.

It would really be unfortunate to allocate resources to fixing a potentially trivial problem. Would love it if we can get WebUSB working again.

**Comment by humanumbrella** [comment]
Sorry for the post/delete spam, I didn't want to send down a wild goose chase but ultimately that's what I'm on.

I am not sure, but I think that this recently added webusb related 'fix' could be the source of the problem --> https://chromium-review.googlesource.com/c/chromium/src/+/2829452

```
usb: Fix crash on Windows when there are no interfaces

This change fixes an invalid pointer read when there are no interfaces
on a USB device, as this leaves the |info| field of the UsbInterfaceInfo
struct uninitialized. To solve this the most commonly used data read
through this pointer is copied directly into the UsbInterfaceInfo struct
and fake data is created when there are no interfaces but the structure
is still needed for internal bookkeeping purposes.

```

We could really use some help from a Ledger dev here.

**Comment by humanumbrella** [comment]
Can confirm that Ledger Nano S / Nano X work fine in Windows Chrome 91.X - so maybe this^ crash fix for Windows breaks it everywhere else? Not sure...

**Comment by MattG561** [comment]
> Can confirm that Ledger Nano S / Nano X work fine in Windows Chrome 91.X - so maybe this^ crash fix for Windows breaks it everywhere else? Not sure...

I'm very surprised that such a large issue hasn't been addressed yet. It's been almost a week without any sign that they're actively working on this.

**Comment by gre** [comment]
Please help us confirm this fixes works https://github.com/LedgerHQ/ledgerjs/releases/tag/v5.53.0
It was validated by us internally but deserve most testing from all various usage of the transport.

I've also deployed a new version of https://ledger-repl.vercel.app/ that ease the test on this and that we can all test to confirm it's working. (project is https://github.com/LedgerHQ/ledger-repl , access to previous version that had the bug https://ledger-repl-a2770cdok.now.sh/ )

**Comment by MattG561** [comment]
> Please help us confirm this fixes works https://github.com/LedgerHQ/ledgerjs/releases/tag/v5.53.0
> It was validated by us internally but deserve most testing from all various usage of the transport.
> 
> I've also deployed a new version of https://ledger-repl.vercel.app/ that ease the test on this and that we can all test to confirm it's working. (project is https://github.com/LedgerHQ/ledger-repl , access to previous version that had the bug https://ledger-repl-a2770cdok.now.sh/ )

The fix for WebUSB is working in our application on Chrome 91.X and MacOS. Can't confirm if it has broken/fixed the issue on Windows 😄.

**Comment by gre** [comment]
@MattG561 @kwunyeung @refi93 @hritique @jacobr & everyone:

Apologies again for a too quick attempt to fix the problem that ends up being incomplete to fully resolve this problem.

I'm issuing right now a 5.53.1 that **will revert the incomplete fix attempt back to 5.52.0**. We are searching for a better solution now.

While the fixes works most of the time, there are cases that we later identified with more extensive QA that makes it actually not "openable" again. As @MattG561 also quickly reported.

Thanks for your reactivity and again sorry for the too fast release. Next time we will do a beta bump version instead of using `"latest"` NPM channel.

---

I'm done on my side for today but we will continue the investigation tomorrow.

One quick thought I had tonight is we may attempt something like (pseudo code)

```
try {
  ...await usual open logic...
} catch (e) {
  if ( ... match the exact error case of the problem ... ) {
    await gracefullyResetDevice(device);
    ... do a new attempt to open logic ... 
  }
}
```

i'm not sure if this idea is viable but worth a try. But more expertise on the topic will be done to maybe rebuild from ground up this transport.

**Comment by gre** [comment]
Could you also share on which OS are we all having issues? We have identified in our side that it's possibly mainly on Mac OS.

**Comment by MattG561** [comment]
@gre The issue mentioned above was solved on my end and was not due to the update (as far as I know). I am still bumping into the same problem you've described above with the device not being openable again. 

Environment info:
macOS Big Sur (version 11.3 20E232)
Chrome version 91.0.4472.77
Ledger Firmware 2.0.0

**Comment by jarcodallo** [comment]
@gre I tried with version `@ledgerhq/hw-transport-webusb@5.53.0`, but got a different this time: `Unknown Status Code: 28161`

Environment info:
macOS Catalina (version 10.15.7 19H15)
Chrome version 91.0.4472.77 (Official Build) (x86_64)
Ledger Firmware 2.0.0

**Comment by pochocosta** [comment]
I'm having the same issue in https://explore-fetchhub.fetch.ai/ and https://cosmoscan.io both in Cosmos ecosystem. But I confirm that I could connect with Metamask (ETH), Zillet.io (Zilliqa), Solflare (Solana) and other apps correctly. The problem for me it's only with apps based in Cosmos.

message: "navigator.usb is undefined"​
name: "TransportOpenUserCancelled"

Environment info:
macOS Big Sur 11.4 (20F71)
Brave Version 1.25.68 Chromium: 91.0.4472.77 (Build oficial) (x86_64) 
Firefox version 89.0 (64-bit)
Cosmos app v2.18.0
Ledger Live v2.26.1

**Comment by humanumbrella** [comment]
@gre `0.53.0` fixed it for us and I believe for a lot of folks based on the mentions of this issue in merges on other projects. I am not sure the details of the problems you all saw that caused revert in `0.53.1`, but we will be sticking with `0.53.0` until Chromium releases the patch reverting the change they made. I had [filed an issue there](https://bugs.chromium.org/p/chromium/issues/detail?id=1215767), which it looks like some other Ledger family members (Steph) have found and commented on.

@jarcodallo You are connecting with the app open on the device, yes? I can confirm that BTC app 1.6.1 with `@ledgerhq/hw-transport-webusb@5.53.0` works in Chromium 91.0.4472.77 on MacOS Big Sur. Maybe there is something different with Catalina and you have to wait for the Chromium update (bug report linked above)

@pochocosta WebUSB does not work in Firefox. It works for us in Chromium 91.X with `@ledgerhq/hw-transport-webusb@5.53.0`

The [Caravan Test Suite](https://unchained-capital.github.io/caravan/#/test) is an easy way to see if it's working with the Bitcoin app.

- Select Ledger
- Then `BEGIN TEST SUITE` 
- Then `START TEST`

 There is no need to restore using the test suite, though you can if you want to. The point is that the test will fail but the device will respond.

**Comment by dotproto** [comment]
Is this issue related to crbug.com/1215767?

**Comment by meriadec** [comment]
FYI there is an active issue on the Chromium project (base project of Chrome) where Ledger took part in the discussion https://bugs.chromium.org/p/chromium/issues/detail?id=1215767

The bug has been identified in Chrome 91 and revert has been successfully tested
For now, it's available on Chrome 93 (Canary, a.k.a developer preview)

official builds can be found here: https://www.google.com/chrome/canary/

it's not clear if the fix is meant to be ported in Chrome 91 / 92, despite some comments on the ticket mention that they are on the fix target
for pessimistic option, you can find the Chrome release schedule here: https://www.chromestatus.com/features/schedule
which say Chrome 93 will be released on Aug 31

**Comment by humanumbrella** [comment]
Afaict this is no longer an issue. [The Chromium issue is closed.](https://bugs.chromium.org/p/chromium/issues/detail?id=1215767) Cheers
