### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TransportError: Invalid channel

### ISSUE THREAD

**Issue by jaybkim1** [LedgerHQ/ledgerjs#62]
This might be a noob question to ask as I don't have much knowledge about JavaScript.

Below are the steps how I installed this project .
(I basically followed the instructions on README.md)

I installed a recent Node.js[v8.9.4] and Yarn [1.3.2].
```
$ git clone https://github.com/LedgerHQ/ledgerjs.git
$ yarn
$ yarn run build
$ yarn run lint
$ yarn test

Done with no errors!
```

Now, I am trying to run index.js, and it triggers the below error.
[I plugged my Ledger with 'no' browser support]

```
$ cd packages/example-node/lib/
$ node index.js

(node:87045) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TransportError: Invalid channel
(node:87045) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is there something that I am missing? 
Anything I need to take a look at?

Any references or directions will be helpful.

Thanks

**Comment by gre** [comment]
Hi @jaybkim1 ,

https://github.com/LedgerHQ/ledgerjs/blob/master/packages/example-node/src/index.js#L1-L12

^as you can see at the moment this 'example-node' app is not doing much, it's just trying to connect to the device and perform a getPublicWalletKey with hw-app-btc . This only works if you have a ledger plugged and with the "Bitcoin" app opened

AFAIK this error "Invalid channel" means you were not into the Bitcoin app when you run the example.

**Comment by jaybkim1** [comment]
@gre 

I only wanted to test if it really connects to the device and extract a public wallet key from my ledger. I had my ledger plugged but not with the "Bitcoin" app opened.
I will try. Thank you for your feedback!

**Comment by jaybkim1** [comment]
Solved it!

Path was the issue.

`const o = await appBtc.getWalletPublicKey("BITCOIN PATH"); `

I will close it.
