### ISSUE TITLE
TransportStatusError while trying to sign an EIP1559 transaction

### ISSUE THREAD

**Issue by fabenedetti** [LedgerHQ/ledgerjs#638]
Hi, 
I'm currently trying to sign an EIP1559 transaction using a Ledger Nano S device but I'm getting a TransportStatusError (  `message: 'Ledger device: UNKNOWN_ERROR (0x6501)',  statusCode: 25857`). I'm using the latest firmware (2.0.0) and the latest ethereum app (1.8.8).

I tried to reproduce the same test from [here](https://github.com/LedgerHQ/ledgerjs/blob/f42e10e90cf57f7e044def8a7d00810e8147ecc1/packages/hw-app-eth/tests/Eth.test.ts#L66) with the physical device but it didn't work. The same code works as expected with a Legacy transaction as input. The code to reproduce it is the following:

```
const Eth = require("@ledgerhq/hw-app-eth").default;
const TransportObject = require("@ledgerhq/hw-transport-node-hid").default;
const { listen } = require("@ledgerhq/logs");

listen(logs => console.log(logs));

(async () => {
    const transport = await TransportObject.create();
    const eth = new Eth(transport);
    const result = await eth.signTransaction(
        "44'/60'/0'/0/0",
        "02ef0306843b9aca008504a817c80082520894b2bb2b958afa2e96dab3f3ce7162b87daea39017872386f26fc1000080c0"
    ).catch(err => console.error(err));
    console.log("Result ", result);
    await transport.close();
})();
```

From the package.json, I'm using the following dependencies
```
 "dependencies": {
    "@ledgerhq/hw-app-eth": "^6.4.0",
    "@ledgerhq/hw-transport-node-hid": "^6.3.0",
    "@ledgerhq/logs": "^6.2.0"
  }
```

This is what I see on the logs
```
{
  type: 'hid-listen',
  id: '1',
  date: 2021-08-03T14:52:23.304Z,
  message: 'attach listener added'
}
{
  type: 'hid-listen',
  id: '2',
  date: 2021-08-03T14:52:23.312Z,
  message: 'detach listener added'
}
{
  type: 'hid-listen',
  id: '3',
  date: 2021-08-03T14:52:23.314Z,
  message: 'Stop received, removing listeners and cancelling pending debounced polls'
}
{
  type: 'apdu',
  id: '4',
  date: 2021-08-03T14:52:23.338Z,
  message: '=> e004000046058000002c8000003c80000000000000000000000002ef0306843b9aca008504a817c80082520894b2bb2b958afa2e96dab3f3ce7162b87daea39017872386f26fc1000080c0'
}
{
  type: 'apdu',
  id: '5',
  date: 2021-08-03T14:52:23.350Z,
  message: '<= 6501'
}
```

and this is the error I receive
```
Error
    at new TransportStatusError (C:\Desarrollo\git-repos\ledger-test\node_modules\@ledgerhq\errors\lib\index.js:184:18)
    at TransportNodeHid.<anonymous> (C:\Desarrollo\git-repos\ledger-test\node_modules\@ledgerhq\hw-transport\lib\Transport.js:123:39)
    at step (C:\Desarrollo\git-repos\ledger-test\node_modules\@ledgerhq\hw-transport\lib\Transport.js:33:23)
    at Object.next (C:\Desarrollo\git-repos\ledger-test\node_modules\@ledgerhq\hw-transport\lib\Transport.js:14:53)
    at fulfilled (C:\Desarrollo\git-repos\ledger-test\node_modules\@ledgerhq\hw-transport\lib\Transport.js:5:58) {
  message: 'Ledger device: UNKNOWN_ERROR (0x6501)',
  statusCode: 25857,
  statusText: 'UNKNOWN_ERROR'
}
```

I'm wondering if this is a bug or if we should wait for an update on firmware device or any of the ledger libraries. 

Thanks.

**Comment by gre** [comment]
@fabenedetti there were both a fix on ledgerjs and in the device app to support these.
- The fix on ledgerjs side was released on Sunday. You need at least 6.3.0 of hw-app-eth
- the fix on device is in Ethereum app v 1.8.9 . @pscott to confirm if it's out yet, but it was not at the time you tested. 

Thanks

**Comment by fabenedetti** [comment]
@gre awesome, that's good news, thanks for your reply!

**Comment by gre** [comment]
@fabenedetti it should be OK now, please confirm. thanks.

**Comment by fabenedetti** [comment]
@gre @pscott it works fine now after updating Ethereum app to v1.9.0. Great work! Thanks.

**Comment by gre** [comment]
Thanks!
