### ISSUE TITLE
hw-app-eth v6.5.0: Truncated chainId showing on device for transactions that are more than 4-bytes long

### ISSUE THREAD

**Issue by danjm** [LedgerHQ/ledgerjs#649]
Hi,

I am updating https://github.com/MetaMask/eth-ledger-bridge-keyring/ to properly take advantage of the change in `@ledgerhq/hw-app-eth` v6.4.1, so that ledger can be used with metamask to sign transactions on networks with chainId's longer than 4-bytes.

Currently, with v6.5.0 of `@ledgerhq/hw-app-eth` and v1.9.2 of the ethereum app on the ledger device, I can successfully sign and send transactions on the palm network.

However, when the network displays on device, it is the truncated chainId that is showing. Palm chainId is 11297108109, but the ledger device displays `Network 44129328`, which I can see from setting breakpoints is the `chainIdTruncated` value set here https://github.com/LedgerHQ/ledgerjs/blob/master/packages/hw-app-eth/src/Eth.ts#L237

I'll add that the chainId is correctly encoded in and recoverable from the `v` property on the signed transaction (in this case it is `0x542b8613d`, and `(parseInt('0x542b8613d', 16) - 35) / 2 === 11297108109`)

Let me know if there is any further information I can provide. I realize there may be an error on my side, or this may be expected until a future update. Any advice in that regard is welcome.

**Comment by pscott** [comment]
https://github.com/LedgerHQ/app-ethereum/pull/183 got merged! This ticket should now be resolved. Please re-open it if you encounter any issues!
