### ISSUE TITLE
Is there a way to retrieve the private key of an account with `ledgerhq/hw-app-btc` ?

### ISSUE THREAD

**Issue by dekadentno** [LedgerHQ/ledgerjs#675]
I've managed to retrieve the address and the public key, but seems like there's nothing implemented for the retrieval of the private key. Does anyone know if there's a workaround for this? Are there any security reasons for not implementing this? Thanks!

**Comment by gre** [comment]
No it's not technically possible to get a private key with hardware wallets.

**Comment by dekadentno** [comment]
Thank you for your answer @gre .
In that case, is there a way to programmatically transfer my funds to another address?
