### ISSUE TITLE
Error: Can't resolve 'fs'  

### ISSUE THREAD

**Issue by sgehrman** [LedgerHQ/ledgerjs#82]
using this: 
    "@ledgerhq/hw-transport-node-hid": "^4.0.0",
    "@ledgerhq/hw-transport-u2f": "^4.0.0",
    "@ledgerhq/hw-app-str": "^4.0.0"

ERROR in ./node_modules/bindings/bindings.js
Module not found: Error: Can't resolve 'fs' in 'f:\Github\stellar-client-web\node_modules\bindings'
 @ ./node_modules/bindings/bindings.js 6:9-22
 @ ./node_modules/node-hid/nodehid.js
 @ ./node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js
 @ ./node_modules/stellar-js-utils/dist/build.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/CreateToken.vue
 @ ./src/pages/CreateToken.vue
 @ ./src/libEntry.js
 @ ./src/entry.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/entry.js

WARNING in ./node_modules/bindings/bindings.js
81:22-40 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/bindings/bindings.js
 @ ./node_modules/node-hid/nodehid.js
 @ ./node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js
 @ ./node_modules/stellar-js-utils/dist/build.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/CreateToken.vue
 @ ./src/pages/CreateToken.vue
 @ ./src/libEntry.js
 @ ./src/entry.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/entry.js

WARNING in ./node_modules/bindings/bindings.js
81:43-53 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/bindings/bindings.js
 @ ./node_modules/node-hid/nodehid.js
 @ ./node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js
 @ ./node_modules/stellar-js-utils/dist/build.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/CreateToken.vue
 @ ./src/pages/CreateToken.vue
 @ ./src/libEntry.js
 @ ./src/entry.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/entry.js

**Comment by gre** [comment]
It looks like you try to use `node-hid` in a web app, it can't work.
For a web app, you shouldn't use `"@ledgerhq/hw-transport-node-hid": "^4.0.0",` because it's meant to run in Node.js. You only need `"@ledgerhq/hw-transport-u2f": "^4.0.0",`, currently the only *transport* that works in a web browser (U2F api).

**Comment by sgehrman** [comment]
yeah, I know, but I have one library that handles both.  Not your fault I guess, but it's annoying.

**Comment by gre** [comment]
not sure if I understood correctly, but maybe you could use 2 different entry points on your library, one for node and one for the browser. It can be done with `"browser"` and `"main"` in package.json
